#include <idc.idc>

// =============================================================
// D2Client_globals.idc  --  generated by gen_ida_idc_globals.ps1 (D2MOO)
// Renames and types global variables.
// 32 globals extracted from D2Client headers.
//
// For each global:
//   set_name(base + offset, name)   -- always applied
//   SetType(base + offset, type)     -- best-effort (needs d2moo_types_for_ida.h)
//
// *** PREREQUISITE for SetType: ***
//   File > Load file > Parse C header file
//   -> select tools/idc/d2moo_types_for_ida.h
// =============================================================

static main()
{
    // Find D2Client segment base dynamically
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2Client") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2Client] ERROR: segment 'D2Client' not found.\n");
        return;
    }
    Message("[D2Client] base=0x%X  (32 globals)\n", base);

    auto addr;
    auto renamed = 0;
    auto typed   = 0;
    auto typeFail = 0;

    // g_nScreenWidth  (extern)
    addr = base + 0xD40EC;
    set_name(addr, "g_nScreenWidth", 0x880); renamed++;
    if (SetType(addr, "int g_nScreenWidth")) typed++; else typeFail++;

    // g_nScreenHeight  (extern)
    addr = base + 0xD40F0;
    set_name(addr, "g_nScreenHeight", 0x880); renamed++;
    if (SetType(addr, "int g_nScreenHeight")) typed++; else typeFail++;

    // g_DisplayPerformanceStats  (extern)
    addr = base + 0xFA980;
    set_name(addr, "g_DisplayPerformanceStats", 0x880); renamed++;
    if (SetType(addr, "BOOL g_DisplayPerformanceStats")) typed++; else typeFail++;

    // D2Client_CriticalSection_A  (extern)
    addr = base + 0x1077D4;
    set_name(addr, "D2Client_CriticalSection_A", 0x880); renamed++;
    if (SetType(addr, "_RTL_CRITICAL_SECTION D2Client_CriticalSection_A")) typed++; else typeFail++;

    // g_pCurrentCharacterName  (extern)
    addr = base + 0x107810;
    set_name(addr, "g_pCurrentCharacterName", 0x880); renamed++;
    if (SetType(addr, "char * g_pCurrentCharacterName")) typed++; else typeFail++;

    // g_nOpenPanels  (extern)
    addr = base + 0x10B9C4;
    set_name(addr, "g_nOpenPanels", 0x880); renamed++;
    if (SetType(addr, "D2C_PanelConfig g_nOpenPanels")) typed++; else typeFail++;

    // g_nPanelCameraOffsetX  (extern)
    addr = base + 0x10B9C0;
    set_name(addr, "g_nPanelCameraOffsetX", 0x880); renamed++;
    if (SetType(addr, "int16_t g_nPanelCameraOffsetX")) typed++; else typeFail++;

    // g_nCameraOriginX  (extern)
    addr = base + 0x10B9BC;
    set_name(addr, "g_nCameraOriginX", 0x880); renamed++;
    if (SetType(addr, "int g_nCameraOriginX")) typed++; else typeFail++;

    // g_nCameraOriginY  (extern)
    addr = base + 0x10B9B8;
    set_name(addr, "g_nCameraOriginY", 0x880); renamed++;
    if (SetType(addr, "int g_nCameraOriginY")) typed++; else typeFail++;

    // g_pCurrentUnit  (extern)
    addr = base + 0x11C200;
    set_name(addr, "g_pCurrentUnit", 0x880); renamed++;
    if (SetType(addr, "D2UnitStrc * g_pCurrentUnit")) typed++; else typeFail++;

    // g_CurrentUnitClientCoordX  (extern)
    addr = base + 0x111A3C;
    set_name(addr, "g_CurrentUnitClientCoordX", 0x880); renamed++;
    if (SetType(addr, "int g_CurrentUnitClientCoordX")) typed++; else typeFail++;

    // g_CurrentUnitClientCoordY  (extern)
    addr = base + 0x111A40;
    set_name(addr, "g_CurrentUnitClientCoordY", 0x880); renamed++;
    if (SetType(addr, "int g_CurrentUnitClientCoordY")) typed++; else typeFail++;

    // g_PreviousUnitClientCoordX  (extern)
    addr = base + 0x111A34;
    set_name(addr, "g_PreviousUnitClientCoordX", 0x880); renamed++;
    if (SetType(addr, "int g_PreviousUnitClientCoordX")) typed++; else typeFail++;

    // g_PreviousUnitClientCoordY  (extern)
    addr = base + 0x111A38;
    set_name(addr, "g_PreviousUnitClientCoordY", 0x880); renamed++;
    if (SetType(addr, "int g_PreviousUnitClientCoordY")) typed++; else typeFail++;

    // g_bHasSelectedUnit  (extern)
    addr = base + 0x10B9E8;
    set_name(addr, "g_bHasSelectedUnit", 0x880); renamed++;
    if (SetType(addr, "BOOL g_bHasSelectedUnit")) typed++; else typeFail++;

    // sgnNumShowItems  (extern)
    addr = base + 0x119428;
    set_name(addr, "sgnNumShowItems", 0x880); renamed++;
    if (SetType(addr, "int sgnNumShowItems")) typed++; else typeFail++;

    // g_D2Client_MenuInfo  (extern)
    addr = base + 0x116FDC;
    set_name(addr, "g_D2Client_MenuInfo", 0x880); renamed++;
    if (SetType(addr, "D2MenuInfoStrc g_D2Client_MenuInfo")) typed++; else typeFail++;

    // g_D2Client_divisor  (extern)
    addr = base + 0xD7BC0;
    set_name(addr, "g_D2Client_divisor", 0x880); renamed++;
    if (SetType(addr, "int g_D2Client_divisor")) typed++; else typeFail++;

    // g_D2CLIENT_offset  (extern)
    addr = base + 0x1119D8;
    set_name(addr, "g_D2CLIENT_offset", 0x880); renamed++;
    if (SetType(addr, "POINT g_D2CLIENT_offset")) typed++; else typeFail++;

    // p_D2Client_Automap_Is_Mini  (extern)
    addr = base + 0x111990;
    set_name(addr, "p_D2Client_Automap_Is_Mini", 0x880); renamed++;
    if (SetType(addr, "BOOL p_D2Client_Automap_Is_Mini")) typed++; else typeFail++;

    // D2Client_GamePacketHandlers  (D2VAR)
    addr = base + 0xD6270;
    set_name(addr, "D2Client_GamePacketHandlers", 0x880); renamed++;
    if (SetType(addr, "GamePacketDesc D2Client_GamePacketHandlers")) typed++; else typeFail++;

    // D2Client_LastGamePacketCmd  (D2VAR)
    addr = base + 0x10B9B4;
    set_name(addr, "D2Client_LastGamePacketCmd", 0x880); renamed++;
    if (SetType(addr, "uint8_t D2Client_LastGamePacketCmd")) typed++; else typeFail++;

    // D2Client_ProcessedGamePacketBytes  (D2VAR)
    addr = base + 0x121AF0;
    set_name(addr, "D2Client_ProcessedGamePacketBytes", 0x880); renamed++;
    if (SetType(addr, "uint32_t D2Client_ProcessedGamePacketBytes")) typed++; else typeFail++;

    // D2Client_CompletedGamePacketBatches  (D2VAR)
    addr = base + 0x121AF8;
    set_name(addr, "D2Client_CompletedGamePacketBatches", 0x880); renamed++;
    if (SetType(addr, "uint32_t D2Client_CompletedGamePacketBatches")) typed++; else typeFail++;

    // D2Client_LargeGamePacketCount  (D2VAR)
    addr = base + 0x121B00;
    set_name(addr, "D2Client_LargeGamePacketCount", 0x880); renamed++;
    if (SetType(addr, "uint32_t D2Client_LargeGamePacketCount")) typed++; else typeFail++;

    // g_AutomapCellGroupByNo  (extern)
    addr = base + 0x10F990;
    set_name(addr, "g_AutomapCellGroupByNo", 0x880); renamed++;
    if (SetType(addr, "uint32_t * g_AutomapCellGroupByNo")) typed++; else typeFail++;

    // g_pAutomapDataPool  (extern)
    addr = base + 0x111998;
    set_name(addr, "g_pAutomapDataPool", 0x880); renamed++;
    if (SetType(addr, "AutomapDataBlock * g_pAutomapDataPool")) typed++; else typeFail++;

    // g_nAutomapDataCount  (extern)
    addr = base + 0x11199C;
    set_name(addr, "g_nAutomapDataCount", 0x880); renamed++;
    if (SetType(addr, "int g_nAutomapDataCount")) typed++; else typeFail++;

    // g_nAutomapUpdateCounter  (extern)
    addr = base + 0x1119E4;
    set_name(addr, "g_nAutomapUpdateCounter", 0x880); renamed++;
    if (SetType(addr, "int g_nAutomapUpdateCounter")) typed++; else typeFail++;

    // g_pAutomapLayers  (extern)
    addr = base + 0x1119A0;
    set_name(addr, "g_pAutomapLayers", 0x880); renamed++;
    if (SetType(addr, "D2AutomapLayerStrc * g_pAutomapLayers")) typed++; else typeFail++;

    // g_pCurrentAutomapLayer  (extern)
    addr = base + 0x1119A4;
    set_name(addr, "g_pCurrentAutomapLayer", 0x880); renamed++;
    if (SetType(addr, "D2AutomapLayerStrc * g_pCurrentAutomapLayer")) typed++; else typeFail++;

    // g_GlobalUnitTables  (extern)
    addr = base + 0x11AA00;
    set_name(addr, "g_GlobalUnitTables", 0x880); renamed++;
    if (SetType(addr, "D2UnitStrc * * g_GlobalUnitTables")) typed++; else typeFail++;

    Message("[D2Client] Globals: %d renamed, %d typed, %d type-fail\n", renamed, typed, typeFail);
    Message("[D2Client] type-fail is normal for struct types not yet in IDA.\n");
}
