#include <idc.idc>

// =============================================================
// D2Client.idc  --  generated by gen_ida_idc_types.ps1 (D2MOO)
// Renames functions via set_name() using base + RVA.
// 65 names extracted from D2Client headers.
//
// TARGET: IDA process dump
// Finds the DLL base by scanning IDA segments for name containing
// "D2Client" -- no hardcoded address needed.
//
// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)
// =============================================================

static Apply_D2Client()
{
    // --- Find module base via segment name ---
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2Client") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2Client] ERROR: no segment with name containing 'D2Client'.\n");
        return;
    }
    Message("[D2Client] base=0x%X\n", base);

    auto renamed = 0;
    auto skipped = 0;

    if (set_name(base + 0xBF80, "GAME_GetFrame", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xC0805, "D2CLIENT_sprintf", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xC2EBE, "D2CLIENT_buf_overflow", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xC2FD6, "D2CLIENT_vsnprintf", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xC3717, "D2CLIENT_putchar_buf", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xC37B5, "D2CLIENT_va_arg_int", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xC42A0, "D2CLIENT_strlen", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xC2E48, "D2CLIENT_format_float", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xB7BC0, "CURSOR_GetMouseX", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xB7BD0, "CURSOR_GetMouseY", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xB370, "GAME_Main", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0xA3B0, "GAME_OpenServerThread", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x9AF0, "GAME_InGameTick", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x9450, "GAME_AllocateGlobals", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x28E0, "GAME_DisplayPerformanceStatistics", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x89450, "D2Client_GetUnitPacketList_6FB29450", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x89480, "D2Client_SetUnitPacketList_6FB29480", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x155C0, "SCMD_FreeUnitPacketList", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x154C0, "SCMD_AllocatePacketListForUnit", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x15610, "SCMD_ProcessUnitPackets", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x11CB0, "SCMD_HandleSystemPacket", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x12190, "SCMD_GameLoad", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x122A0, "SCMD_SetClientIsInSight", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x12310, "SCMD_UnsetClientIsInSight", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x12970, "SCMD_UnitWarpXY", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x12A80, "SCMD_ReassignUnit", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x12B00, "SCMD_MultipleSetAttributes", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x12F10, "SCMD_SetAttribute", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x13570, "SCMD_SKILLS_AssignSkill", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x13610, "SCMD_UpdateUnitEx", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x13670, "SCMD_SKILLS_SetQuantity", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x13E90, "SCMD_UNITS_SetPlayerPortalFlags", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x13ED0, "SCMD_UNITS_SetObjectPortalFlags", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x143E0, "SCMD_WeaponSwap", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x14420, "SCMD_UnitAction", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x14590, "SCMD_AssignNPC", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x14700, "SCMD_UnitStateOnEx", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x14750, "SCMD_UnitStateOnValEx", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x14900, "SCMD_UnitStateOffEx", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x14950, "SCMD_UnitStateAllEx", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x14B40, "SCMD_HealthUpdate", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x14BD0, "SCMD_NewMonsterEx", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x15090, "SCMD_SetViewPos", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x150B0, "SCMD_ParseGamePacket", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x15960, "SELECT_UpdateCameraOriginFromOpenPanels", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x15A20, "SELECT_GetSelectedItem", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x1D330, "SKILLS_HandleDualWieldAlternateSwing", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x2BA40, "AUTOMAP_AllocCell", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x2BAF0, "AUTOMAP_Update", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x2CD50, "AUTOMAP_AVL_Insert", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x2D3C0, "AUTOMAP_AVL_AddTile", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x2D560, "AUTOMAP_AVL_AddObject", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x2D180, "AUTOMAP_RevealLayerRoom", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x2D660, "AUTOMAP_RevealRoom", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x2C610, "AUTOMAP_Layer_Load", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x2BCD0, "AUTOMAP_Layer_Save", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x69F60, "UI_DrawGroundItemLabels", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x11A778, "UI_GetDisplayItemText", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x883D0, "UNIT_GetCurrentUnit", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x89370, "UNIT_GetCurrentUnitRoom", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x869F0, "UNIT_GetUnitFromIndex", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x86C90, "UNIT_GetRoomAtSubtileCoords", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x886F0, "UNIT_TestSelect", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x88020, "UNIT_AllocateGlobalTables", 0x880)) renamed++; else skipped++;
    if (set_name(base + 0x897F0, "UNIT_GetUnitName", 0x880)) renamed++; else skipped++;

    Message("[D2Client] Renamed: %d ok, %d skipped/failed\n", renamed, skipped);
}

#ifndef D2MOO_ALL_IDC
static main() { Apply_D2Client(); }
#endif
