#include <idc.idc>

// =============================================================
// D2Client_types.idc  --  generated by gen_ida_idc_types.ps1 (D2MOO)
// Applies function type signatures via SetType().
// 54 signatures extracted from D2Client headers.
//
// *** PREREQUISITE: Load D2MOO types into IDA first ***
//   File > Load file > Parse C header file
//   -> select tools/idc/d2moo_types_for_ida.h  (see README_types.md)
// Without this, SetType() will fail on any function using custom structs.
// =============================================================

static main()
{
    // Find D2Client segment base dynamically
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2Client") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2Client] ERROR: segment 'D2Client' not found.\n");
        return;
    }
    Message("[D2Client] base=0x%X\n", base);

    auto addr;
    auto ok = 0;
    auto fail = 0;

    addr = base + 0xBF80; MakeFunction(addr, BADADDR); if (SetType(addr, "int GAME_GetFrame()")) ok++; else { Message("[FAIL] 0x%X  int GAME_GetFrame()\n", addr); fail++; }
    addr = base + 0xC0805; MakeFunction(addr, BADADDR); if (SetType(addr, "int D2CLIENT_sprintf(_BYTE *buffer, const char *format, ...)")) ok++; else { Message("[FAIL] 0x%X  int D2CLIENT_sprintf(_BYTE *buffer, const char *format, ...)\n", addr); fail++; }
    addr = base + 0xC2EBE; MakeFunction(addr, BADADDR); if (SetType(addr, "int __cdecl D2CLIENT_buf_overflow(unsigned __int8 c, _DWORD *stream_ctx)")) ok++; else { Message("[FAIL] 0x%X  int __cdecl D2CLIENT_buf_overflow(unsigned __int8 c, _DWORD *stream_ctx)\n", addr); fail++; }
    addr = base + 0xC2FD6; MakeFunction(addr, BADADDR); if (SetType(addr, "int __cdecl D2CLIENT_vsnprintf(int *stream_ctx, const char *format, va_list args)")) ok++; else { Message("[FAIL] 0x%X  int __cdecl D2CLIENT_vsnprintf(int *stream_ctx, const char *format, va_list args)\n", addr); fail++; }
    addr = base + 0xC3717; MakeFunction(addr, BADADDR); if (SetType(addr, "_DWORD *__cdecl D2CLIENT_putchar_buf(unsigned __int8 c, _DWORD *stream_ctx, _DWORD *pCount)")) ok++; else { Message("[FAIL] 0x%X  _DWORD *__cdecl D2CLIENT_putchar_buf(unsigned __int8 c, _DWORD *stream_ctx, _DWORD *pCount)\n", addr); fail++; }
    addr = base + 0xC37B5; MakeFunction(addr, BADADDR); if (SetType(addr, "int __cdecl D2CLIENT_va_arg_int(va_list *ap)")) ok++; else { Message("[FAIL] 0x%X  int __cdecl D2CLIENT_va_arg_int(va_list *ap)\n", addr); fail++; }
    addr = base + 0xC42A0; MakeFunction(addr, BADADDR); if (SetType(addr, "char *__cdecl D2CLIENT_strlen(_DWORD *str)")) ok++; else { Message("[FAIL] 0x%X  char *__cdecl D2CLIENT_strlen(_DWORD *str)\n", addr); fail++; }
    addr = base + 0xC2E48; MakeFunction(addr, BADADDR); if (SetType(addr, "int __cdecl D2CLIENT_format_float(int value, int buffer, int fmt_char, int precision, int flags)")) ok++; else { Message("[FAIL] 0x%X  int __cdecl D2CLIENT_format_float(int value, int buffer, int fmt_char, int precision, int flags)\n", addr); fail++; }
    addr = base + 0xB7BC0; MakeFunction(addr, BADADDR); if (SetType(addr, "int CURSOR_GetMouseX()")) ok++; else { Message("[FAIL] 0x%X  int CURSOR_GetMouseX()\n", addr); fail++; }
    addr = base + 0xB7BD0; MakeFunction(addr, BADADDR); if (SetType(addr, "int CURSOR_GetMouseY()")) ok++; else { Message("[FAIL] 0x%X  int CURSOR_GetMouseY()\n", addr); fail++; }
    addr = base + 0xB370; MakeFunction(addr, BADADDR); if (SetType(addr, "int GAME_Main()")) ok++; else { Message("[FAIL] 0x%X  int GAME_Main()\n", addr); fail++; }
    addr = base + 0xA3B0; MakeFunction(addr, BADADDR); if (SetType(addr, "DWORD __stdcall GAME_OpenServerThread(LPVOID a1)")) ok++; else { Message("[FAIL] 0x%X  DWORD __stdcall GAME_OpenServerThread(LPVOID a1)\n", addr); fail++; }
    addr = base + 0x9AF0; MakeFunction(addr, BADADDR); if (SetType(addr, "int __stdcall GAME_InGameTick()")) ok++; else { Message("[FAIL] 0x%X  int __stdcall GAME_InGameTick()\n", addr); fail++; }
    addr = base + 0x9450; MakeFunction(addr, BADADDR); if (SetType(addr, "int GAME_AllocateGlobals()")) ok++; else { Message("[FAIL] 0x%X  int GAME_AllocateGlobals()\n", addr); fail++; }
    addr = base + 0x28E0; MakeFunction(addr, BADADDR); if (SetType(addr, "void GAME_DisplayPerformanceStatistics()")) ok++; else { Message("[FAIL] 0x%X  void GAME_DisplayPerformanceStatistics()\n", addr); fail++; }
    addr = base + 0x89450; MakeFunction(addr, BADADDR); if (SetType(addr, "D2ClientUnitPacketListStrc* __fastcall D2Client_GetUnitPacketList_6FB29450(D2UnitStrc * pUnit)")) ok++; else { Message("[FAIL] 0x%X  D2ClientUnitPacketListStrc* __fastcall D2Client_GetUnitPacketList_6FB29450(D2UnitStrc * pUnit)\n", addr); fail++; }
    addr = base + 0x89480; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall D2Client_SetUnitPacketList_6FB29480(D2UnitStrc* pUnit, D2PacketListStrc* pPacketList)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall D2Client_SetUnitPacketList_6FB29480(D2UnitStrc* pUnit, D2PacketListStrc* pPacketList)\n", addr); fail++; }
    addr = base + 0x155C0; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_FreeUnitPacketList(D2UnitStrc* pUnit)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_FreeUnitPacketList(D2UnitStrc* pUnit)\n", addr); fail++; }
    addr = base + 0x154C0; MakeFunction(addr, BADADDR); if (SetType(addr, "D2ClientUnitPacketListStrc* __fastcall SCMD_AllocatePacketListForUnit(D2UnitStrc* pUnit)")) ok++; else { Message("[FAIL] 0x%X  D2ClientUnitPacketListStrc* __fastcall SCMD_AllocatePacketListForUnit(D2UnitStrc* pUnit)\n", addr); fail++; }
    addr = base + 0x15610; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_ProcessUnitPackets(D2UnitStrc* pUnit)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_ProcessUnitPackets(D2UnitStrc* pUnit)\n", addr); fail++; }
    addr = base + 0x11CB0; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_HandleSystemPacket(uint8_t* pPacketBuffer, int nPacketSize)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_HandleSystemPacket(uint8_t* pPacketBuffer, int nPacketSize)\n", addr); fail++; }
    addr = base + 0x12190; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_GameLoad(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_GameLoad(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x122A0; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_SetClientIsInSight(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_SetClientIsInSight(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x12310; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_UnsetClientIsInSight(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_UnsetClientIsInSight(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x12970; MakeFunction(addr, BADADDR); if (SetType(addr, "D2UnitStrc *__fastcall SCMD_UnitWarpXY(UnitWarpXY *arg)")) ok++; else { Message("[FAIL] 0x%X  D2UnitStrc *__fastcall SCMD_UnitWarpXY(UnitWarpXY *arg)\n", addr); fail++; }
    addr = base + 0x12A80; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_ReassignUnit(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_ReassignUnit(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x12B00; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_MultipleSetAttributes(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_MultipleSetAttributes(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x12F10; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_SetAttribute(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_SetAttribute(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x13570; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_SKILLS_AssignSkill(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_SKILLS_AssignSkill(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x13610; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_UpdateUnitEx(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_UpdateUnitEx(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x13670; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_SKILLS_SetQuantity(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_SKILLS_SetQuantity(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x13E90; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_UNITS_SetPlayerPortalFlags(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_UNITS_SetPlayerPortalFlags(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x13ED0; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_UNITS_SetObjectPortalFlags(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_UNITS_SetObjectPortalFlags(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x143E0; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_WeaponSwap(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_WeaponSwap(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x14420; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_UnitAction(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_UnitAction(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x14590; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_AssignNPC(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_AssignNPC(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x14700; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_UnitStateOnEx(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_UnitStateOnEx(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x14750; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_UnitStateOnValEx(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_UnitStateOnValEx(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x14900; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_UnitStateOffEx(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_UnitStateOffEx(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x14950; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_UnitStateAllEx(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_UnitStateAllEx(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x14B40; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_HealthUpdate(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_HealthUpdate(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x14BD0; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_NewMonsterEx(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_NewMonsterEx(D2UnitStrc* pUnit, D2PacketBufferStrc* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x15090; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_SetViewPos(uint8_t* pPacketBuffer)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_SetViewPos(uint8_t* pPacketBuffer)\n", addr); fail++; }
    addr = base + 0x150B0; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SCMD_ParseGamePacket(uint8_t *pPacketBuffer, uint32_t nPacketSize)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SCMD_ParseGamePacket(uint8_t *pPacketBuffer, uint32_t nPacketSize)\n", addr); fail++; }
    addr = base + 0x15960; MakeFunction(addr, BADADDR); if (SetType(addr, "BOOL SELECT_UpdateCameraOriginFromOpenPanels()")) ok++; else { Message("[FAIL] 0x%X  BOOL SELECT_UpdateCameraOriginFromOpenPanels()\n", addr); fail++; }
    addr = base + 0x15A20; MakeFunction(addr, BADADDR); if (SetType(addr, "D2UnitStrc *SELECT_GetSelectedItem()")) ok++; else { Message("[FAIL] 0x%X  D2UnitStrc *SELECT_GetSelectedItem()\n", addr); fail++; }
    addr = base + 0x1D330; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall SKILLS_HandleDualWieldAlternateSwing(D2UnitStrc *pUnit, _DWORD *swingState)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall SKILLS_HandleDualWieldAlternateSwing(D2UnitStrc *pUnit, _DWORD *swingState)\n", addr); fail++; }
    addr = base + 0x69F60; MakeFunction(addr, BADADDR); if (SetType(addr, "void __usercall UI_DrawGroundItemLabels(DrawMode drawMode@<edi>)")) ok++; else { Message("[FAIL] 0x%X  void __usercall UI_DrawGroundItemLabels(DrawMode drawMode@<edi>)\n", addr); fail++; }
    addr = base + 0x80740; MakeFunction(addr, BADADDR); if (SetType(addr, "void __fastcall UI_GetDisplayItemText(D2UnitStrc *a1, Unicode *szItemName, int nSize)")) ok++; else { Message("[FAIL] 0x%X  void __fastcall UI_GetDisplayItemText(D2UnitStrc *a1, Unicode *szItemName, int nSize)\n", addr); fail++; }
    addr = base + 0x869F0; MakeFunction(addr, BADADDR); if (SetType(addr, "D2UnitStrc *__fastcall UNIT_GetUnitFromIndex(int dwUnitId, D2C_UnitTypes unitType)")) ok++; else { Message("[FAIL] 0x%X  D2UnitStrc *__fastcall UNIT_GetUnitFromIndex(int dwUnitId, D2C_UnitTypes unitType)\n", addr); fail++; }
    addr = base + 0x86C90; MakeFunction(addr, BADADDR); if (SetType(addr, "D2ActiveRoomStrc *__fastcall UNIT_GetRoomAtSubtileCoords(int32_t x, int32_t y)")) ok++; else { Message("[FAIL] 0x%X  D2ActiveRoomStrc *__fastcall UNIT_GetRoomAtSubtileCoords(int32_t x, int32_t y)\n", addr); fail++; }
    addr = base + 0x886F0; MakeFunction(addr, BADADDR); if (SetType(addr, "int __fastcall UNIT_TestSelect(D2UnitStrc *pUnit, int a2, int a3, int a4)")) ok++; else { Message("[FAIL] 0x%X  int __fastcall UNIT_TestSelect(D2UnitStrc *pUnit, int a2, int a3, int a4)\n", addr); fail++; }
    addr = base + 0x88020; MakeFunction(addr, BADADDR); if (SetType(addr, "int UNIT_AllocateGlobalTables()")) ok++; else { Message("[FAIL] 0x%X  int UNIT_AllocateGlobalTables()\n", addr); fail++; }
    addr = base + 0x897F0; MakeFunction(addr, BADADDR); if (SetType(addr, "Unicode *__fastcall UNIT_GetUnitName(D2UnitStrc *pUnit)")) ok++; else { Message("[FAIL] 0x%X  Unicode *__fastcall UNIT_GetUnitName(D2UnitStrc *pUnit)\n", addr); fail++; }

    Message("[D2Client] Types applied: %d ok, %d failed\n", ok, fail);
    Message("[D2Client] If fail > 0, run: File > Load file > Parse C header file\n");
    Message("[D2Client]   -> select tools/idc/d2moo_types_for_ida.h\n");
}
