#include <idc.idc>

// =============================================================
// D2CMP.idc  --  generated by gen_ida_idc.ps1 (D2MOO)
// Source : D2CMP.1.10f.def  (24 exported symbols)
//
// TARGET: IDA process dump
//
// Finds the DLL base by scanning IDA segments for name containing
// "D2CMP" -- no hardcoded address needed.
//
// Then parses the PE export table at that base and applies names.
//   funcAddr = base + Dword(addrOfFunctions + (ordinal - ordBase) * 4)
//
// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)
// =============================================================

static Apply_D2CMP()
{
    // --- Find module base via segment name ---
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2CMP") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2CMP] ERROR: no segment with name containing 'D2CMP'.\n");
        Message("[D2CMP] Check segment names with: Edit > Segments\n");
        return;
    }

    // --- Parse PE header ---
    auto peBase = base + Dword(base + 0x3C);
    if (Dword(peBase) != 0x00004550) {
        Message("[D2CMP] ERROR: invalid PE signature at 0x%X (base=0x%X)\n", peBase, base);
        Message("[D2CMP] The first matching segment does not hold the PE header.\n");
        Message("[D2CMP] Try running ParseExports.idc first to confirm the correct base.\n");
        return;
    }

    // --- Export Directory ---
    auto exportRVA = Dword(peBase + 0x18 + 0x60);  // OptionalHeader + DataDirectory[0]
    if (exportRVA == 0) {
        Message("[D2CMP] ERROR: no export directory found.\n");
        return;
    }
    auto exportDir   = base + exportRVA;
    auto ordBase     = Dword(exportDir + 0x10);  // IMAGE_EXPORT_DIRECTORY.Base
    auto addrFuncs   = base + Dword(exportDir + 0x1C);  // .AddressOfFunctions

    Message("[D2CMP] base=0x%X  ordBase=%d  addrFuncs=0x%X\n", base, ordBase, addrFuncs);

    // --- Apply names ---
    auto rva;
    auto renamed = 0;
    auto skipped = 0;

    rva = Dword(addrFuncs + (10004 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_GetNearestPaletteIndex", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10024 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_CelFileNormalize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10032 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_CelFileFreeHardware", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10036 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_CelGetHandle", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10037 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_CelGetWidth", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10038 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_CelGetHeight", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10039 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_CelGetOffsetX", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10040 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_CelGetOffsetY", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10046 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_CelFileGetCelsPerDirection", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10051 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_GetGfxFileExtension", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10052 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_InitSpriteCache", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10053 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_FlushSpriteCache", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10054 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_SetCompressedDataMode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10077 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_10077_GetTileType", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10078 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_10078_GetTileStyle", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10079 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_10079_GetTileFlags", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10081 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_10081_GetTileRarity", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10082 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_10082_GetTileSequence", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10085 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_10085_GetTileFlagArray", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10087 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_10087_LoadTileLibrarySlot", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10088 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_10088_GetTiles", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10098 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_MixPalette", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10099 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_SpriteFreeAsyncLoads", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10102 - ordBase) * 4); if (rva) { set_name(base + rva, "D2CMP_TileFreeAsyncLoads", 0x880); renamed++; } else skipped++;

    Message("[D2CMP] Done: %d renamed, %d skipped (rva==0)\n", renamed, skipped);
}

#ifndef D2MOO_ALL_IDC
static main() { Apply_D2CMP(); }
#endif
