#include <idc.idc>

// =============================================================
// D2Common_globals.idc  --  generated by gen_ida_idc_globals.ps1 (D2MOO)
// Renames and types global variables.
// 2 globals extracted from D2Common headers.
//
// For each global:
//   set_name(base + offset, name)   -- always applied
//   SetType(base + offset, type)     -- best-effort (needs d2moo_types_for_ida.h)
//
// *** PREREQUISITE for SetType: ***
//   File > Load file > Parse C header file
//   -> select tools/idc/d2moo_types_for_ida.h
// =============================================================

static Apply_D2Common_globals()
{
    // Find D2Common segment base dynamically
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2Common") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2Common] ERROR: segment 'D2Common' not found.\n");
        return;
    }
    Message("[D2Common] base=0x%X  (2 globals)\n", base);

    auto addr;
    auto renamed = 0;
    auto typed   = 0;
    auto typeFail = 0;

    // gpLvlSubTypeFilesCriticalSection  (extern)
    addr = base + 0xAA704;
    set_name(addr, "gpLvlSubTypeFilesCriticalSection", 0x880); renamed++;
    if (SetType(addr, "LPCRITICAL_SECTION gpLvlSubTypeFilesCriticalSection")) typed++; else typeFail++;

    // DATATBLS_LoadFromBin  (extern)
    addr = base + 0x96A24;
    set_name(addr, "DATATBLS_LoadFromBin", 0x880); renamed++;
    if (SetType(addr, "BOOL DATATBLS_LoadFromBin")) typed++; else typeFail++;

    Message("[D2Common] Globals: %d renamed, %d typed, %d type-fail\n", renamed, typed, typeFail);
    Message("[D2Common] type-fail is normal for struct types not yet in IDA.\n");
}

#ifndef D2MOO_ALL_IDC
static main() { Apply_D2Common_globals(); }
#endif
