#include <idc.idc>

// =============================================================
// D2Game.idc  --  generated by gen_ida_idc.ps1 (D2MOO)
// Source : D2Game.1.10f.def  (59 exported symbols)
//
// TARGET: IDA process dump
//
// Finds the DLL base by scanning IDA segments for name containing
// "D2Game" -- no hardcoded address needed.
//
// Then parses the PE export table at that base and applies names.
//   funcAddr = base + Dword(addrOfFunctions + (ordinal - ordBase) * 4)
//
// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)
// =============================================================

static main()
{
    // --- Find module base via segment name ---
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2Game") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2Game] ERROR: no segment with name containing 'D2Game'.\n");
        Message("[D2Game] Check segment names with: Edit > Segments\n");
        return;
    }

    // --- Parse PE header ---
    auto peBase = base + Dword(base + 0x3C);
    if (Dword(peBase) != 0x00004550) {
        Message("[D2Game] ERROR: invalid PE signature at 0x%X (base=0x%X)\n", peBase, base);
        Message("[D2Game] The first matching segment does not hold the PE header.\n");
        Message("[D2Game] Try running ParseExports.idc first to confirm the correct base.\n");
        return;
    }

    // --- Export Directory ---
    auto exportRVA = Dword(peBase + 0x18 + 0x60);  // OptionalHeader + DataDirectory[0]
    if (exportRVA == 0) {
        Message("[D2Game] ERROR: no export directory found.\n");
        return;
    }
    auto exportDir   = base + exportRVA;
    auto ordBase     = Dword(exportDir + 0x10);  // IMAGE_EXPORT_DIRECTORY.Base
    auto addrFuncs   = base + Dword(exportDir + 0x1C);  // .AddressOfFunctions

    Message("[D2Game] base=0x%X  ordBase=%d  addrFuncs=0x%X\n", base, ordBase, addrFuncs);

    // --- Apply names ---
    auto rva;
    auto renamed = 0;
    auto skipped = 0;

    rva = Dword(addrFuncs + (10001 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10001_Return0", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10002 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_InitGameDataTable", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10003 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_ProcessNetworkMessages", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10004 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_UpdateGamesProgress", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10005 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_UpdateClients", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10006 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_CloseAllGames", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10007 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_ReceiveDatabaseCharacter", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10008 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10008", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10009 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_SetGlobalAct", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10010 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_SetInitSeed", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10011 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10011", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10012 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_GetGamesCount", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10013 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10013", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10014 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_GetGameInformation", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10015 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_GetGameServerGameIds", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10016 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_GetPlayerUnitsCount", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10017 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_GetPlayerUnitsInfo", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10018 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10018", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10019 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_GetUnitsDescriptions", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10020 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_GetStatistics", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10021 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_SendMessageToAllClients", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10022 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_SendMessageToGameClients", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10023 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_SetServerCallbackFunctions", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10024 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10024_RemoveClientFromGame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10025 - ordBase) * 4); if (rva) { set_name(base + rva, "DEBUG_GetUnitFromTypeAndGUID", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10026 - ordBase) * 4); if (rva) { set_name(base + rva, "DEBUG_GetAct", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10027 - ordBase) * 4); if (rva) { set_name(base + rva, "DEBUG_GetFreeMonsterIndex", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10028 - ordBase) * 4); if (rva) { set_name(base + rva, "DEBUG_GetRoomBySubtileCoordinates", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10029 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GAME_10029_SAVE_WriteFileInterface", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10033 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10033", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10034 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10034_Return", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10035 - ordBase) * 4); if (rva) { set_name(base + rva, "QUESTS_DisableSequences", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10036 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GAME_10036_PLRSAVE_EnableSaveFileWriting", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10037 - ordBase) * 4); if (rva) { set_name(base + rva, "QUESTS_CheckFirstPickedSet", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10038 - ordBase) * 4); if (rva) { set_name(base + rva, "QUESTS_CheckNotIntroQuest", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10039 - ordBase) * 4); if (rva) { set_name(base + rva, "TASK_InitializeClock", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10040 - ordBase) * 4); if (rva) { set_name(base + rva, "TASK_FreeAllQueueSlots", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10041 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10041_TASK_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10042 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10042", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10043 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10043", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10044 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10044", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10045 - ordBase) * 4); if (rva) { set_name(base + rva, "TASK_ProcessGame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10046 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10046", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10047 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_CreateNewEmptyGame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10048 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10048_Return1", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10049 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10049_Return1", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10050 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10050", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10051 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10051", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10052 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_GetMemoryUsage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10053 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10053", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10054 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10054", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10055 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_DisconnectClientByName", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10056 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10056", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10057 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10057", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10058 - ordBase) * 4); if (rva) { set_name(base + rva, "CLIENTS_GetExpansionClientCount", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10059 - ordBase) * 4); if (rva) { set_name(base + rva, "PLAYER_SetVirtualPlayerCount", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10060 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10060_Return", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10061 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Game_10061_Return", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10062 - ordBase) * 4); if (rva) { set_name(base + rva, "GAME_ReturnArgument", 0x880); renamed++; } else skipped++;

    Message("[D2Game] Done: %d renamed, %d skipped (rva==0)\n", renamed, skipped);
}
