#include <idc.idc>

// =============================================================
// D2gfx.idc  --  generated by gen_ida_idc.ps1 (D2MOO)
// Source : D2gfx.1.10f.def  (82 exported symbols)
//
// TARGET: IDA process dump
//
// Finds the DLL base by scanning IDA segments for name containing
// "D2Gfx" -- no hardcoded address needed.
//
// Then parses the PE export table at that base and applies names.
//   funcAddr = base + Dword(addrOfFunctions + (ordinal - ordBase) * 4)
//
// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)
// =============================================================

static Apply_D2gfx()
{
    // --- Find module base via segment name ---
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2Gfx") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2gfx] ERROR: no segment with name containing 'D2Gfx'.\n");
        Message("[D2gfx] Check segment names with: Edit > Segments\n");
        return;
    }

    // --- Parse PE header ---
    auto peBase = base + Dword(base + 0x3C);
    if (Dword(peBase) != 0x00004550) {
        Message("[D2gfx] ERROR: invalid PE signature at 0x%X (base=0x%X)\n", peBase, base);
        Message("[D2gfx] The first matching segment does not hold the PE header.\n");
        Message("[D2gfx] Try running ParseExports.idc first to confirm the correct base.\n");
        return;
    }

    // --- Export Directory ---
    auto exportRVA = Dword(peBase + 0x18 + 0x60);  // OptionalHeader + DataDirectory[0]
    if (exportRVA == 0) {
        Message("[D2gfx] ERROR: no export directory found.\n");
        return;
    }
    auto exportDir   = base + exportRVA;
    auto ordBase     = Dword(exportDir + 0x10);  // IMAGE_EXPORT_DIRECTORY.Base
    auto addrFuncs   = base + Dword(exportDir + 0x1C);  // .AddressOfFunctions

    Message("[D2gfx] base=0x%X  ordBase=%d  addrFuncs=0x%X\n", base, ordBase, addrFuncs);

    // --- Apply names ---
    auto rva;
    auto renamed = 0;
    auto skipped = 0;

    rva = Dword(addrFuncs + (10000 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_Initialize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10001 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_Release", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10002 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_ReturnFalse", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10003 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_GetDisplayType", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10004 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_CheckWindowed", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10005 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_GetResolutionMode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10007 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_CheckUnitPerspective", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10008 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_SetUnitPerspective", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10009 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_TogglePerspective", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10010 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_CheckPerspective", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10011 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_SetPerspective", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10012 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_ToggleBlendedShadows", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10013 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_CheckBlendedShadows", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10014 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_SetBlendShadows", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10015 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_ToggleLowQuality", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10016 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_CheckLowQuality", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10017 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_SetLowQuality", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10018 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_SetGamma", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10019 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_GammaCanBeControlled", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10020 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_EnableVSync", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10021 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_GetCacheResults", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10022 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_SetViewMatrixAdjust", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10023 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10024 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10025 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_SetPaused", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10026 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_GetState", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10027 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_GetWindow", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10028 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_IsFullScreen", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10029 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_ShowCursor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10030 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_Resize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10031 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_ClearCaches", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10032 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_PlayCutscene", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10033 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_EndCutScene", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10034 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_OpenSmackCutscene", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10035 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_CheckCutScene", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10036 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_DecodeSmacker", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10037 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_PlaySmacker", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10038 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_CloseSmacker", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10039 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_UpdatePlacement", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10040 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_ShowAll", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10041 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_GetDimensions", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10042 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_SetOption", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10043 - ordBase) * 4); if (rva) { set_name(base + rva, "WINDOW_Activate", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10044 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_StartDraw", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10045 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_EndScene", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10046 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_GetBackBuffer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10047 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_HardwareAcceleratedRenderMode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10048 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_SetPalette", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10049 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_SetPaletteTables", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10050 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_SetAmbientColor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10051 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_UtilDiamond", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10052 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_UtilRect", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10053 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_UtilFilledRect", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10054 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_UtilPoint", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10055 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_DrawBox", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10056 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_DrawBoxAlpha", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10057 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_DrawLine", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10058 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_ClearScreen", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10059 - ordBase) * 4); if (rva) { set_name(base + rva, "SCALE_UpdateFactor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10060 - ordBase) * 4); if (rva) { set_name(base + rva, "SCALE_GetFactor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10061 - ordBase) * 4); if (rva) { set_name(base + rva, "SCALE_SetDefaultFactor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10062 - ordBase) * 4); if (rva) { set_name(base + rva, "SCALE_IncreaseFactor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10063 - ordBase) * 4); if (rva) { set_name(base + rva, "SCALE_DecreaseFactor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10064 - ordBase) * 4); if (rva) { set_name(base + rva, "SCALE_SetPerspectiveScale", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10065 - ordBase) * 4); if (rva) { set_name(base + rva, "SCALE_CheckPerspectivePosition", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10066 - ordBase) * 4); if (rva) { set_name(base + rva, "SCALE_AdjustPerspectivePosition", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10067 - ordBase) * 4); if (rva) { set_name(base + rva, "SCALE_ScalePerspectivePosition", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10068 - ordBase) * 4); if (rva) { set_name(base + rva, "SCALE_SetDefaultFactorPerspectiveFactor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10069 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_OutputString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10070 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_DebugDraw", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10071 - ordBase) * 4); if (rva) { set_name(base + rva, "TEXTURE_CelFlatSpriteDraw", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10072 - ordBase) * 4); if (rva) { set_name(base + rva, "TEXTURE_CelDraw", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10073 - ordBase) * 4); if (rva) { set_name(base + rva, "TEXTURE_CelDrawColor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10074 - ordBase) * 4); if (rva) { set_name(base + rva, "TEXTURE_CelDrawEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10075 - ordBase) * 4); if (rva) { set_name(base + rva, "TEXTURE_CelDrawShadow", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10076 - ordBase) * 4); if (rva) { set_name(base + rva, "TEXTURE_CelDrawHilight", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10077 - ordBase) * 4); if (rva) { set_name(base + rva, "TEXTURE_CelDrawClipped", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10078 - ordBase) * 4); if (rva) { set_name(base + rva, "TEXTURE_DebugFillBackBuffer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10079 - ordBase) * 4); if (rva) { set_name(base + rva, "D2GFX_FloorTileDraw", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10080 - ordBase) * 4); if (rva) { set_name(base + rva, "TILE_TileDrawLit", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10081 - ordBase) * 4); if (rva) { set_name(base + rva, "TILE_TileDrawTrans", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10082 - ordBase) * 4); if (rva) { set_name(base + rva, "TILE_ShadowTileDraw", 0x880); renamed++; } else skipped++;

    Message("[D2gfx] Done: %d renamed, %d skipped (rva==0)\n", renamed, skipped);
}

#ifndef D2MOO_ALL_IDC
static main() { Apply_D2gfx(); }
#endif
