#include <idc.idc>

// =============================================================
// D2Lang.idc  --  generated by gen_ida_idc.ps1 (D2MOO)
// Source : D2Lang.1.10f.def  (42 exported symbols)
//
// TARGET: IDA process dump
//
// Finds the DLL base by scanning IDA segments for name containing
// "D2Lang" -- no hardcoded address needed.
//
// Then parses the PE export table at that base and applies names.
//   funcAddr = base + Dword(addrOfFunctions + (ordinal - ordBase) * 4)
//
// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)
// =============================================================

static Apply_D2Lang()
{
    // --- Find module base via segment name ---
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2Lang") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2Lang] ERROR: no segment with name containing 'D2Lang'.\n");
        Message("[D2Lang] Check segment names with: Edit > Segments\n");
        return;
    }

    // --- Parse PE header ---
    auto peBase = base + Dword(base + 0x3C);
    if (Dword(peBase) != 0x00004550) {
        Message("[D2Lang] ERROR: invalid PE signature at 0x%X (base=0x%X)\n", peBase, base);
        Message("[D2Lang] The first matching segment does not hold the PE header.\n");
        Message("[D2Lang] Try running ParseExports.idc first to confirm the correct base.\n");
        return;
    }

    // --- Export Directory ---
    auto exportRVA = Dword(peBase + 0x18 + 0x60);  // OptionalHeader + DataDirectory[0]
    if (exportRVA == 0) {
        Message("[D2Lang] ERROR: no export directory found.\n");
        return;
    }
    auto exportDir   = base + exportRVA;
    auto ordBase     = Dword(exportDir + 0x10);  // IMAGE_EXPORT_DIRECTORY.Base
    auto addrFuncs   = base + Dword(exportDir + 0x1C);  // .AddressOfFunctions

    Message("[D2Lang] base=0x%X  ordBase=%d  addrFuncs=0x%X\n", base, ordBase, addrFuncs);

    // --- Apply names ---
    auto rva;
    auto renamed = 0;
    auto skipped = 0;

    rva = Dword(addrFuncs + (10014 - ordBase) * 4); if (rva) { set_name(base + rva, "??0Unicode@@QAE@G@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10015 - ordBase) * 4); if (rva) { set_name(base + rva, "??4Unicode@@QAEAAU0@ABU0@@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10016 - ordBase) * 4); if (rva) { set_name(base + rva, "??BUnicode@@QBEGXZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10017 - ordBase) * 4); if (rva) { set_name(base + rva, "??_FUnicode@@QAEXXZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10019 - ordBase) * 4); if (rva) { set_name(base + rva, "?_toLowerTable@Unicode@@0PAGA", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10020 - ordBase) * 4); if (rva) { set_name(base + rva, "?_toUpperTable@Unicode@@0PAGA", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10021 - ordBase) * 4); if (rva) { set_name(base + rva, "?compare@Unicode@@QBEHU1@@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10022 - ordBase) * 4); if (rva) { set_name(base + rva, "?compare@Unicode@@SIHU1@0@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10023 - ordBase) * 4); if (rva) { set_name(base + rva, "?directionality@Unicode@@QAE?AW4Direction@1@XZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10024 - ordBase) * 4); if (rva) { set_name(base + rva, "?isASCII@Unicode@@QBEHXZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10025 - ordBase) * 4); if (rva) { set_name(base + rva, "?isAlpha@Unicode@@QBEHXZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10027 - ordBase) * 4); if (rva) { set_name(base + rva, "?isLineBreak@Unicode@@SIHPBU1@I@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10028 - ordBase) * 4); if (rva) { set_name(base + rva, "?isNewline@Unicode@@QBEHXZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10029 - ordBase) * 4); if (rva) { set_name(base + rva, "?isPipe@Unicode@@QBEHXZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10030 - ordBase) * 4); if (rva) { set_name(base + rva, "?isWhitespace@Unicode@@QBEHXZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10031 - ordBase) * 4); if (rva) { set_name(base + rva, "?isWordEnd@Unicode@@SIHPBU1@I@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10033 - ordBase) * 4); if (rva) { set_name(base + rva, "?sprintf@Unicode@@SAXHPAU1@PBU1@ZZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10034 - ordBase) * 4); if (rva) { set_name(base + rva, "?strcat@Unicode@@SIPAU1@PAU1@PBU1@@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10035 - ordBase) * 4); if (rva) { set_name(base + rva, "?strchr@Unicode@@SIPAU1@PBU1@U1@@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10036 - ordBase) * 4); if (rva) { set_name(base + rva, "?strcmp@Unicode@@SIHPBU1@0@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10038 - ordBase) * 4); if (rva) { set_name(base + rva, "?strcpy@Unicode@@SIPAU1@PAU1@PBU1@@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10039 - ordBase) * 4); if (rva) { set_name(base + rva, "?stricmp@Unicode@@SIHPBU1@0@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10040 - ordBase) * 4); if (rva) { set_name(base + rva, "?strlen@Unicode@@SIHPBU1@@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10041 - ordBase) * 4); if (rva) { set_name(base + rva, "?strncat@Unicode@@SIPAU1@PAU1@PBU1@H@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10042 - ordBase) * 4); if (rva) { set_name(base + rva, "?strncmp@Unicode@@SIHPBU1@0I@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10044 - ordBase) * 4); if (rva) { set_name(base + rva, "?strncpy@Unicode@@SIPAU1@PAU1@PBU1@H@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10045 - ordBase) * 4); if (rva) { set_name(base + rva, "?strnicmp@Unicode@@SIHPBU1@0I@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10046 - ordBase) * 4); if (rva) { set_name(base + rva, "?strstr@Unicode@@SIPAU1@PBU1@0@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10050 - ordBase) * 4); if (rva) { set_name(base + rva, "?toLower@Unicode@@QBE?AU1@XZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10051 - ordBase) * 4); if (rva) { set_name(base + rva, "?toUnicode@Unicode@@SIPAU1@PAU1@PBDH@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10052 - ordBase) * 4); if (rva) { set_name(base + rva, "?toUpper@Unicode@@QBE?AU1@XZ", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10053 - ordBase) * 4); if (rva) { set_name(base + rva, "?toUtf@Unicode@@SIPADPADPBU1@H@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10055 - ordBase) * 4); if (rva) { set_name(base + rva, "?unicode2Win@Unicode@@SIPADPADPBU1@H@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10059 - ordBase) * 4); if (rva) { set_name(base + rva, "?utf8ToUnicode@Unicode@@SIPAU1@PAU1@PBDH@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10062 - ordBase) * 4); if (rva) { set_name(base + rva, "?win2Unicode@Unicode@@SIPAU1@PAU1@PBDH@Z", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10003 - ordBase) * 4); if (rva) { set_name(base + rva, "D2LANG_GetStringByReferenceString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10004 - ordBase) * 4); if (rva) { set_name(base + rva, "D2LANG_GetStringFromTblIndex", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10005 - ordBase) * 4); if (rva) { set_name(base + rva, "CRC16_CalculateChecksum", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10007 - ordBase) * 4); if (rva) { set_name(base + rva, "STRTABLE_GetLanguage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10009 - ordBase) * 4); if (rva) { set_name(base + rva, "STR_GroupIntDigits", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10010 - ordBase) * 4); if (rva) { set_name(base + rva, "STR_GroupUintDigits", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10013 - ordBase) * 4); if (rva) { set_name(base + rva, "D2LANG_GetTblIndex", 0x880); renamed++; } else skipped++;

    Message("[D2Lang] Done: %d renamed, %d skipped (rva==0)\n", renamed, skipped);
}

#ifndef D2MOO_ALL_IDC
static main() { Apply_D2Lang(); }
#endif
