#include <idc.idc>

// =============================================================
// D2Net.idc  --  generated by gen_ida_idc.ps1 (D2MOO)
// Source : D2Net.1.10f.def  (40 exported symbols)
//
// TARGET: IDA process dump
//
// Finds the DLL base by scanning IDA segments for name containing
// "D2Net" -- no hardcoded address needed.
//
// Then parses the PE export table at that base and applies names.
//   funcAddr = base + Dword(addrOfFunctions + (ordinal - ordBase) * 4)
//
// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)
// =============================================================

static main()
{
    // --- Find module base via segment name ---
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2Net") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2Net] ERROR: no segment with name containing 'D2Net'.\n");
        Message("[D2Net] Check segment names with: Edit > Segments\n");
        return;
    }

    // --- Parse PE header ---
    auto peBase = base + Dword(base + 0x3C);
    if (Dword(peBase) != 0x00004550) {
        Message("[D2Net] ERROR: invalid PE signature at 0x%X (base=0x%X)\n", peBase, base);
        Message("[D2Net] The first matching segment does not hold the PE header.\n");
        Message("[D2Net] Try running ParseExports.idc first to confirm the correct base.\n");
        return;
    }

    // --- Export Directory ---
    auto exportRVA = Dword(peBase + 0x18 + 0x60);  // OptionalHeader + DataDirectory[0]
    if (exportRVA == 0) {
        Message("[D2Net] ERROR: no export directory found.\n");
        return;
    }
    auto exportDir   = base + exportRVA;
    auto ordBase     = Dword(exportDir + 0x10);  // IMAGE_EXPORT_DIRECTORY.Base
    auto addrFuncs   = base + Dword(exportDir + 0x1C);  // .AddressOfFunctions

    Message("[D2Net] base=0x%X  ordBase=%d  addrFuncs=0x%X\n", base, ordBase, addrFuncs);

    // --- Apply names ---
    auto rva;
    auto renamed = 0;
    auto skipped = 0;

    rva = Dword(addrFuncs + (10000 - ordBase) * 4); if (rva) { set_name(base + rva, "CLIENT_Initialize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10001 - ordBase) * 4); if (rva) { set_name(base + rva, "CLIENT_Release", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10002 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_WaitForSingleObject", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10003 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_Initialize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10004 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_Release", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10005 - ordBase) * 4); if (rva) { set_name(base + rva, "CLIENT_Send", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10006 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10006", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10007 - ordBase) * 4); if (rva) { set_name(base + rva, "CLIENT_DequeueGamePacket", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10008 - ordBase) * 4); if (rva) { set_name(base + rva, "CLIENT_DequeueSystemPacket", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10010 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_ReadFromMessageList1", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10011 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_ReadFromMessageList0", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10012 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_ReadFromMessageList2", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10013 - ordBase) * 4); if (rva) { set_name(base + rva, "CLIENT_GetLocalIpAddressString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10014 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_GetIpAddressStringFromClientId", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10015 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10015", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10016 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10016", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10017 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10017", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10018 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10018", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10019 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10019", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10020 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_SetClientGameGUID", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10021 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_GetClientGameGUID", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10022 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10022", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10023 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_SetHackListEnabled", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10024 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_WSAGetLastError", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10025 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10025", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10026 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_SetMaxClientsPerGame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10027 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10027", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10028 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10028_Return", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10029 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10029_Return", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10030 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_GetServerPacketSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10031 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_GetClientPacketSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10032 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10032", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10033 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10033", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10034 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10034", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10035 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10035", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10036 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10036", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10037 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_GetSocketFromClientId", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10038 - ordBase) * 4); if (rva) { set_name(base + rva, "SERVER_GetIpAddressFromClientId", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10039 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10039", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10040 - ordBase) * 4); if (rva) { set_name(base + rva, "D2NET_10040", 0x880); renamed++; } else skipped++;

    Message("[D2Net] Done: %d renamed, %d skipped (rva==0)\n", renamed, skipped);
}
