#include <idc.idc>

// =============================================================
// D2Sound.idc  --  generated by gen_ida_idc.ps1 (D2MOO)
// Source : D2Sound.1.10f.def  (10 exported symbols)
//
// TARGET: IDA process dump
//
// Finds the DLL base by scanning IDA segments for name containing
// "D2Sound" -- no hardcoded address needed.
//
// Then parses the PE export table at that base and applies names.
//   funcAddr = base + Dword(addrOfFunctions + (ordinal - ordBase) * 4)
//
// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)
// =============================================================

static main()
{
    // --- Find module base via segment name ---
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2sound") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2Sound] ERROR: no segment with name containing 'D2Sound'.\n");
        Message("[D2Sound] Check segment names with: Edit > Segments\n");
        return;
    }

    // --- Parse PE header ---
    auto peBase = base + Dword(base + 0x3C);
    if (Dword(peBase) != 0x00004550) {
        Message("[D2Sound] ERROR: invalid PE signature at 0x%X (base=0x%X)\n", peBase, base);
        Message("[D2Sound] The first matching segment does not hold the PE header.\n");
        Message("[D2Sound] Try running ParseExports.idc first to confirm the correct base.\n");
        return;
    }

    // --- Export Directory ---
    auto exportRVA = Dword(peBase + 0x18 + 0x60);  // OptionalHeader + DataDirectory[0]
    if (exportRVA == 0) {
        Message("[D2Sound] ERROR: no export directory found.\n");
        return;
    }
    auto exportDir   = base + exportRVA;
    auto ordBase     = Dword(exportDir + 0x10);  // IMAGE_EXPORT_DIRECTORY.Base
    auto addrFuncs   = base + Dword(exportDir + 0x1C);  // .AddressOfFunctions

    Message("[D2Sound] base=0x%X  ordBase=%d  addrFuncs=0x%X\n", base, ordBase, addrFuncs);

    // --- Apply names ---
    auto rva;
    auto renamed = 0;
    auto skipped = 0;

    rva = Dword(addrFuncs + (10000 - ordBase) * 4); if (rva) { set_name(base + rva, "D2SOUND_OpenSoundSystem", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10001 - ordBase) * 4); if (rva) { set_name(base + rva, "D2SOUND_CloseSoundSystem", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10034 - ordBase) * 4); if (rva) { set_name(base + rva, "D2SOUND_10034", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10039 - ordBase) * 4); if (rva) { set_name(base + rva, "D2SOUND_10039", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10048 - ordBase) * 4); if (rva) { set_name(base + rva, "D2SOUND_10048", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10049 - ordBase) * 4); if (rva) { set_name(base + rva, "D2SOUND_10049", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10065 - ordBase) * 4); if (rva) { set_name(base + rva, "D2SOUND_10065", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10066 - ordBase) * 4); if (rva) { set_name(base + rva, "D2SOUND_10066", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10069 - ordBase) * 4); if (rva) { set_name(base + rva, "D2SOUND_10069", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10070 - ordBase) * 4); if (rva) { set_name(base + rva, "D2SOUND_10070", 0x880); renamed++; } else skipped++;

    Message("[D2Sound] Done: %d renamed, %d skipped (rva==0)\n", renamed, skipped);
}
