#include <idc.idc>

// =============================================================
// D2Win.idc  --  generated by gen_ida_idc.ps1 (D2MOO)
// Source : D2Win.1.10f.def  (208 exported symbols)
//
// TARGET: IDA process dump
//
// Finds the DLL base by scanning IDA segments for name containing
// "D2Win" -- no hardcoded address needed.
//
// Then parses the PE export table at that base and applies names.
//   funcAddr = base + Dword(addrOfFunctions + (ordinal - ordBase) * 4)
//
// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)
// =============================================================

static main()
{
    // --- Find module base via segment name ---
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "D2Win") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[D2Win] ERROR: no segment with name containing 'D2Win'.\n");
        Message("[D2Win] Check segment names with: Edit > Segments\n");
        return;
    }

    // --- Parse PE header ---
    auto peBase = base + Dword(base + 0x3C);
    if (Dword(peBase) != 0x00004550) {
        Message("[D2Win] ERROR: invalid PE signature at 0x%X (base=0x%X)\n", peBase, base);
        Message("[D2Win] The first matching segment does not hold the PE header.\n");
        Message("[D2Win] Try running ParseExports.idc first to confirm the correct base.\n");
        return;
    }

    // --- Export Directory ---
    auto exportRVA = Dword(peBase + 0x18 + 0x60);  // OptionalHeader + DataDirectory[0]
    if (exportRVA == 0) {
        Message("[D2Win] ERROR: no export directory found.\n");
        return;
    }
    auto exportDir   = base + exportRVA;
    auto ordBase     = Dword(exportDir + 0x10);  // IMAGE_EXPORT_DIRECTORY.Base
    auto addrFuncs   = base + Dword(exportDir + 0x1C);  // .AddressOfFunctions

    Message("[D2Win] base=0x%X  ordBase=%d  addrFuncs=0x%X\n", base, ordBase, addrFuncs);

    // --- Apply names ---
    auto rva;
    auto renamed = 0;
    auto skipped = 0;

    rva = Dword(addrFuncs + (10000 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_CreateWindow", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10001 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_InitializeSpriteCache", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10002 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_CloseSpriteCache", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10003 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10003", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10004 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10004", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10005 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10005", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10006 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10006_ClearDrawCaches", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10007 - ordBase) * 4); if (rva) { set_name(base + rva, "BACKGROUND_SetCellFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10008 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10008", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10009 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10009", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10010 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10010", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10011 - ordBase) * 4); if (rva) { set_name(base + rva, "CURSOR_SetCellFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10012 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10012", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10013 - ordBase) * 4); if (rva) { set_name(base + rva, "CONTROL_SetCellFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10014 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10014_SetWndProc", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10015 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10015", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10016 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10016", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10017 - ordBase) * 4); if (rva) { set_name(base + rva, "CONTROL_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10018 - ordBase) * 4); if (rva) { set_name(base + rva, "CONTROL_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10019 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10019", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10020 - ordBase) * 4); if (rva) { set_name(base + rva, "WREGISTER_RegisterCommand", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10021 - ordBase) * 4); if (rva) { set_name(base + rva, "WREGISTER_UnregisterCommand", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10022 - ordBase) * 4); if (rva) { set_name(base + rva, "WREGISTER_RegisterCommands", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10023 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10023", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10024 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10024_CONTROL_CheckFirstFlag", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10025 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10025_CONTROL_ToggleFirstFlag", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10026 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10026_CONTROL_CheckThirdFlag", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10027 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10027_CONTROL_ToggleThirdFlag", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10028 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10028", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10029 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10029", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10030 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10030_CONTROL_ToggleFourthFlag", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10031 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10031", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10032 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_IsMouseButtonPressed", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10033 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10033", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10034 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10034_MixRGB", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10035 - ordBase) * 4); if (rva) { set_name(base + rva, "CONTROL_GetType", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10036 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_FreeArchives", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10037 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_LoadArchives", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10038 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_GetArchive", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10039 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_LoadCellFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10040 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_LoadCellFileWithFileSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10041 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_FreeCellFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10042 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10042_TEXTBOX_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10043 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10043_TEXTBOX_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10044 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10044", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10045 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10045", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10046 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10046", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10047 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10047", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10048 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10048", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10049 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10049", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10050 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10050_TEXTBOX_SetLine", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10051 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10051", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10052 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10052_TEXTBOX_GetNumLines", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10053 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10053", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10054 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10054", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10055 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10055", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10056 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10056", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10057 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10057", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10058 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10058_0", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10059 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10059", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10060 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10060", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10061 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10061", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10062 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10062", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10063 - ordBase) * 4); if (rva) { set_name(base + rva, "SCROLLBAR_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10064 - ordBase) * 4); if (rva) { set_name(base + rva, "SCROLLBAR_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10065 - ordBase) * 4); if (rva) { set_name(base + rva, "SCROLLBAR_GetMaxSteps", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10066 - ordBase) * 4); if (rva) { set_name(base + rva, "SCROLLBAR_SetMaxSteps", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10067 - ordBase) * 4); if (rva) { set_name(base + rva, "SCROLLBAR_GetCurrentStep", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10068 - ordBase) * 4); if (rva) { set_name(base + rva, "SCROLLBAR_SetCurrentStep", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10069 - ordBase) * 4); if (rva) { set_name(base + rva, "SCROLLBAR_SetTextBox", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10070 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10070_EDITBOX_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10071 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10071_EDITBOX_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10072 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10072", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10073 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10073", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10074 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10074", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10075 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10075", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10076 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10076", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10077 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10077_EDITBOX_GetText", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10078 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10078_IsNumber", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10079 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10079_IsLetter", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10080 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10080_EDITBOX_SetNextEditBox", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10081 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10081", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10082 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10082", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10083 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10083", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10084 - ordBase) * 4); if (rva) { set_name(base + rva, "IMAGE2_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10085 - ordBase) * 4); if (rva) { set_name(base + rva, "IMAGE_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10086 - ordBase) * 4); if (rva) { set_name(base + rva, "IMAGE_SetCellFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10087 - ordBase) * 4); if (rva) { set_name(base + rva, "IMAGE_SetCoordinates", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10088 - ordBase) * 4); if (rva) { set_name(base + rva, "IMAGE_SetFrame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10089 - ordBase) * 4); if (rva) { set_name(base + rva, "IMAGE_ForceNormalDrawMode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10090 - ordBase) * 4); if (rva) { set_name(base + rva, "IMAGE_GetFrameCount", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10091 - ordBase) * 4); if (rva) { set_name(base + rva, "PROGRESSBAR_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10092 - ordBase) * 4); if (rva) { set_name(base + rva, "PROGRESSBAR_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10093 - ordBase) * 4); if (rva) { set_name(base + rva, "PROGRESSBAR_SetProgress", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10094 - ordBase) * 4); if (rva) { set_name(base + rva, "POPUP_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10095 - ordBase) * 4); if (rva) { set_name(base + rva, "POPUP_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10096 - ordBase) * 4); if (rva) { set_name(base + rva, "POPUP_AddLine", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10097 - ordBase) * 4); if (rva) { set_name(base + rva, "SMACK_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10098 - ordBase) * 4); if (rva) { set_name(base + rva, "SMACK_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10099 - ordBase) * 4); if (rva) { set_name(base + rva, "SMACK_Decode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10100 - ordBase) * 4); if (rva) { set_name(base + rva, "SMACK_SetCoordinates", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10101 - ordBase) * 4); if (rva) { set_name(base + rva, "SMACK_DeleteFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10102 - ordBase) * 4); if (rva) { set_name(base + rva, "ANIMIMAGE_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10103 - ordBase) * 4); if (rva) { set_name(base + rva, "ANIMIMAGE_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10104 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10104", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10105 - ordBase) * 4); if (rva) { set_name(base + rva, "ANIMIMAGE_SetIsRunning", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10106 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10106", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10107 - ordBase) * 4); if (rva) { set_name(base + rva, "BUTTON_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10108 - ordBase) * 4); if (rva) { set_name(base + rva, "BUTTON_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10109 - ordBase) * 4); if (rva) { set_name(base + rva, "BUTTON_IsPressed", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10110 - ordBase) * 4); if (rva) { set_name(base + rva, "BUTTON_SetIsPressed", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10111 - ordBase) * 4); if (rva) { set_name(base + rva, "BUTTON_SetTextWithStringId", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10112 - ordBase) * 4); if (rva) { set_name(base + rva, "BUTTON_SetCoordinates", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10113 - ordBase) * 4); if (rva) { set_name(base + rva, "BUTTON_SimulateClick", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10114 - ordBase) * 4); if (rva) { set_name(base + rva, "BUTTON_SetBaseFrame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10115 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10115_FONT", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10116 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10116", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10117 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10117_DrawText", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10118 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10118_DrawBlendedText", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10119 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10119_DrawCroppedText", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10120 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10120", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10121 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10121_GetTextWidth", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10122 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10122", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10123 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10123", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10124 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10124", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10125 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10125", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10126 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10126_DrawTextFromCache", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10127 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10127_SetFont", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10128 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10128", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10129 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10129_DrawFramedText", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10130 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10130_DrawFramedTextEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10131 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10131_GetTextDimensions", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10132 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10132", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10133 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10133", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10134 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10134_DrawCellFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10135 - ordBase) * 4); if (rva) { set_name(base + rva, "LIST_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10136 - ordBase) * 4); if (rva) { set_name(base + rva, "LIST_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10137 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10137", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10138 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10138", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10139 - ordBase) * 4); if (rva) { set_name(base + rva, "LIST_GetSelectedDataIndex", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10140 - ordBase) * 4); if (rva) { set_name(base + rva, "LIST_GetDataFromIndex", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10141 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10141", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10142 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10142_CompUnitDestroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10143 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10143", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10144 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10144", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10145 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10145", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10146 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10146", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10147 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10147", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10149 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10149", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10150 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10150", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10151 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10151", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10152 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10152", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10153 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10153", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10154 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10154", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10155 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10155", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10156 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10156", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10157 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10157", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10158 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10158", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10159 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10159", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10160 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10160_GetPlayerTitle", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10161 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10161", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10162 - ordBase) * 4); if (rva) { set_name(base + rva, "ACCOUNTLIST_Create", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10163 - ordBase) * 4); if (rva) { set_name(base + rva, "ACCOUNTLIST_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10164 - ordBase) * 4); if (rva) { set_name(base + rva, "ACCOUNTLIST_FreeData", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10165 - ordBase) * 4); if (rva) { set_name(base + rva, "ACCOUNTLIST_AllocData", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10166 - ordBase) * 4); if (rva) { set_name(base + rva, "ACCOUNTLIST_RemoveEntry", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10167 - ordBase) * 4); if (rva) { set_name(base + rva, "ACCOUNTLIST_GetTextFromSelectedEntry", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10168 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10168_WINMAIN_CreateScreenshot", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10169 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10169", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10170 - ordBase) * 4); if (rva) { set_name(base + rva, "CONTROL_MouseInsideRect", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10171 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_LoadExpansionArchives", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10172 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_LoadVideoArchives", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10173 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_UnloadExpansionArchives", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10174 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_ShowInsertPlayDiscMessage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10175 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10175_GetPL2Shift", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10176 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10176", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10177 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10177", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10178 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10178", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10179 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10179", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10180 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10180", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10181 - ordBase) * 4); if (rva) { set_name(base + rva, "TIMER_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10182 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10182", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10183 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_ShowInsertCinematicsDisc", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10184 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10184", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10185 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10185", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10186 - ordBase) * 4); if (rva) { set_name(base + rva, "BUTTON_SetText", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10187 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10187", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10188 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10188", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10189 - ordBase) * 4); if (rva) { set_name(base + rva, "BUTTON_SetStringId", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10190 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10190", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10191 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10191", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10192 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10192", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10193 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10193", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10194 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10194", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10195 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10195", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10196 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10196", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10197 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10197", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10198 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10198", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10199 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10199", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10200 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10200", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10201 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10201", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10202 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10202", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10203 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10203_TEXTBOX", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10204 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10204", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10205 - ordBase) * 4); if (rva) { set_name(base + rva, "ARCHIVE_ShowInsertExpansionDiscMessage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10206 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10206", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10207 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10207", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10208 - ordBase) * 4); if (rva) { set_name(base + rva, "D2Win_10208", 0x880); renamed++; } else skipped++;

    Message("[D2Win] Done: %d renamed, %d skipped (rva==0)\n", renamed, skipped);
}
