#include <idc.idc>

// =============================================================
// Fog.idc  --  generated by gen_ida_idc.ps1 (D2MOO)
// Source : Fog.1.10f.def  (138 exported symbols)
//
// TARGET: IDA process dump
//
// Finds the DLL base by scanning IDA segments for name containing
// "Fog" -- no hardcoded address needed.
//
// Then parses the PE export table at that base and applies names.
//   funcAddr = base + Dword(addrOfFunctions + (ordinal - ordBase) * 4)
//
// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)
// =============================================================

static main()
{
    // --- Find module base via segment name ---
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "Fog") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[Fog] ERROR: no segment with name containing 'Fog'.\n");
        Message("[Fog] Check segment names with: Edit > Segments\n");
        return;
    }

    // --- Parse PE header ---
    auto peBase = base + Dword(base + 0x3C);
    if (Dword(peBase) != 0x00004550) {
        Message("[Fog] ERROR: invalid PE signature at 0x%X (base=0x%X)\n", peBase, base);
        Message("[Fog] The first matching segment does not hold the PE header.\n");
        Message("[Fog] Try running ParseExports.idc first to confirm the correct base.\n");
        return;
    }

    // --- Export Directory ---
    auto exportRVA = Dword(peBase + 0x18 + 0x60);  // OptionalHeader + DataDirectory[0]
    if (exportRVA == 0) {
        Message("[Fog] ERROR: no export directory found.\n");
        return;
    }
    auto exportDir   = base + exportRVA;
    auto ordBase     = Dword(exportDir + 0x10);  // IMAGE_EXPORT_DIRECTORY.Base
    auto addrFuncs   = base + Dword(exportDir + 0x1C);  // .AddressOfFunctions

    Message("[Fog] base=0x%X  ordBase=%d  addrFuncs=0x%X\n", base, ordBase, addrFuncs);

    // --- Apply names ---
    auto rva;
    auto renamed = 0;
    auto skipped = 0;

    rva = Dword(addrFuncs + (10259 - ordBase) * 4); if (rva) { set_name(base + rva, "gdwBitMasks", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10260 - ordBase) * 4); if (rva) { set_name(base + rva, "gdwInvBitMasks", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10000 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_CloseSocket", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10001 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_WSAStartup", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10002 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_WSACleanup", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10003 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_Connect", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10004 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_ConnectEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10005 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_Destroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10006 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_Receive", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10007 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_Send", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10008 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_Select", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10009 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_SendNoLock", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10010 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_Lock", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10011 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_Unlock", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10012 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_GetPeerName", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10013 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_GetHostIPAddress", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10014 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_inet_ntoa", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10015 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_ResolveHostIPAddress", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10016 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_GetError", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10017 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SOCKET_SetBlockingMode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10018 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_csprintf", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10019 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_InitErrorMgr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10021 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SetLogPrefix", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10022 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_GetSystemInfo", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10023 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_DisplayAssert", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10024 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_DisplayHalt", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10025 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_DisplayWarning", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10026 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_DisplayError", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10029 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_Trace", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10030 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_TraceF", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10031 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_TraceAppend", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10032 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_TraceMemory", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10033 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_CrashDeadlockDetected", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10039 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_IsHandlingError", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10042 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_Alloc", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10043 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_Free", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10044 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_Realloc", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10045 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AllocPool", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10046 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_FreePool", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10047 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_ReallocPool", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10050 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10050_EnterCriticalSection", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10052 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_GetMemoryUsage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10055 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10055_GetSyncTime", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10082 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10082_Noop", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10083 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10083_Cos_LUT", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10084 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10084_Sin_LUT", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10085 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_Decode14BitsFromString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10086 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_Encode14BitsToString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10087 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_Decode32BitsFromString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10088 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_Encode32BitsToString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10089 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataInitialize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10090 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataDestroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10091 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataLoadFileEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10092 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataTestLoaded", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10093 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataWaitAndGetBuffer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10094 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataGetBuffer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10095 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataGetBufferSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10096 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataSetResults", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10097 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataFree", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10099 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataSetPriority", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10100 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AsyncDataHandlePriorityChanges", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10101 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_MPQSetConfig", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10102 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_FOpenFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10103 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_FCloseFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10104 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_FReadFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10105 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_FGetFileSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10106 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_FSetFilePointer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10107 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_CreateFileA", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10108 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_DeleteFileA", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10109 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_CloseFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10115 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_GetSavePath", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10116 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_GetInstallPath", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10117 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_UseDirect", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10118 - ordBase) * 4); if (rva) { set_name(base + rva, "BITMANIP_SetBitState", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10119 - ordBase) * 4); if (rva) { set_name(base + rva, "BITMANIP_GetBitState", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10120 - ordBase) * 4); if (rva) { set_name(base + rva, "BITMANIP_MaskBitstate", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10126 - ordBase) * 4); if (rva) { set_name(base + rva, "BITMANIP_Initialize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10127 - ordBase) * 4); if (rva) { set_name(base + rva, "BITMANIP_GetSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10128 - ordBase) * 4); if (rva) { set_name(base + rva, "BITMANIP_Write", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10129 - ordBase) * 4); if (rva) { set_name(base + rva, "BITMANIP_ReadSigned", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10130 - ordBase) * 4); if (rva) { set_name(base + rva, "BITMANIP_Read", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10131 - ordBase) * 4); if (rva) { set_name(base + rva, "BITMANIP_GoToNextByte", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10137 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_ComputeStringCRC16", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10142 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_CreateNewPoolSystem", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10143 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_DestroyMemoryPoolSystem", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10145 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SetMemoryPoolSystemMode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10149 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_InitializeServer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10151 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SetMaxClientsPerGame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10152 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10152", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10154 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_WaitForSingleObject", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10156 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10156", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10157 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10157", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10158 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10158", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10159 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10159", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10161 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10161", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10162 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10162", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10163 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10163", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10164 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10164", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10165 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10165", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10166 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10166", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10170 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10170", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10171 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10171", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10172 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10172", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10173 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10173", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10175 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10175", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10176 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_IsWindowsNT", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10177 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10177", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10178 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_SetHackListEnabled", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10180 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10180", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10181 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10181", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10182 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10182_Return", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10183 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10183_Return", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10186 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10186", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10187 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10187", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10207 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10207", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10208 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_CreateBinFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10209 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_FreeBinFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10210 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_GetRecordCountFromBinFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10211 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_AllocLinker", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10212 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_FreeLinker", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10213 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_GetLinkIndex", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10214 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_GetStringFromLinkIndex", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10215 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10215", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10216 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10216_AddRecordToLinkingTable", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10217 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_GetRowFromTxt", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10218 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10218", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10219 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10219", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10222 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10222", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10223 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10223", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10224 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10224", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10227 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_IsExpansion", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10229 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_ComputeChecksum", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10230 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_PopCount", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10233 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10233", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10252 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_LeadingZeroesCount", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10253 - ordBase) * 4); if (rva) { set_name(base + rva, "DATATBLS_CalcEvaluateExpression", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10254 - ordBase) * 4); if (rva) { set_name(base + rva, "DATATBLS_CompileExpression", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (10255 - ordBase) * 4); if (rva) { set_name(base + rva, "FOG_10255", 0x880); renamed++; } else skipped++;

    Message("[Fog] Done: %d renamed, %d skipped (rva==0)\n", renamed, skipped);
}
