#include <idc.idc>

// =============================================================
// Storm.idc  --  generated by gen_ida_idc.ps1 (D2MOO)
// Source : Storm.1.10f.def  (361 exported symbols)
//
// TARGET: IDA process dump
//
// Finds the DLL base by scanning IDA segments for name containing
// "Storm" -- no hardcoded address needed.
//
// Then parses the PE export table at that base and applies names.
//   funcAddr = base + Dword(addrOfFunctions + (ordinal - ordBase) * 4)
//
// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)
// =============================================================

static Apply_Storm()
{
    // --- Find module base via segment name ---
    auto base = BADADDR;
    auto seg;
    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {
        if (strstr(get_segm_name(seg), "Storm") != -1) {
            base = SegStart(seg);
            break;
        }
    }
    if (base == BADADDR) {
        Message("[Storm] ERROR: no segment with name containing 'Storm'.\n");
        Message("[Storm] Check segment names with: Edit > Segments\n");
        return;
    }

    // --- Parse PE header ---
    auto peBase = base + Dword(base + 0x3C);
    if (Dword(peBase) != 0x00004550) {
        Message("[Storm] ERROR: invalid PE signature at 0x%X (base=0x%X)\n", peBase, base);
        Message("[Storm] The first matching segment does not hold the PE header.\n");
        Message("[Storm] Try running ParseExports.idc first to confirm the correct base.\n");
        return;
    }

    // --- Export Directory ---
    auto exportRVA = Dword(peBase + 0x18 + 0x60);  // OptionalHeader + DataDirectory[0]
    if (exportRVA == 0) {
        Message("[Storm] ERROR: no export directory found.\n");
        return;
    }
    auto exportDir   = base + exportRVA;
    auto ordBase     = Dword(exportDir + 0x10);  // IMAGE_EXPORT_DIRECTORY.Base
    auto addrFuncs   = base + Dword(exportDir + 0x1C);  // .AddressOfFunctions

    Message("[Storm] base=0x%X  ordBase=%d  addrFuncs=0x%X\n", base, ordBase, addrFuncs);

    // --- Apply names ---
    auto rva;
    auto renamed = 0;
    auto skipped = 0;

    rva = Dword(addrFuncs + (101 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetCreateGame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (102 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetDestroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (103 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetEnumProviders", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (104 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetEnumDevices", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (105 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetEnumGames", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (106 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetDropPlayer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (107 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetGetGameInfo", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (108 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetGetNetworkLatency", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (109 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetGetNumPlayers", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (110 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetGetOwnerTurnsWaiting", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (111 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetGetPerformanceData", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (112 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetGetPlayerCaps", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (113 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetGetPlayerName", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (114 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetGetProviderCaps", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (115 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetGetTurnsInTransit", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (116 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetInitializeDevice", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (117 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetInitializeProvider", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (118 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetJoinGame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (119 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetLeaveGame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (120 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetPerformUpgrade", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (121 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetReceiveMessage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (122 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetReceiveTurns", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (123 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetRegisterEventHandler", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (124 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetResetLatencyMeasurements", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (125 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetSelectGame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (126 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetSelectProvider", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (127 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetSendMessage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (128 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetSendTurn", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (129 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetSetBasePlayer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (130 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetSetGameMode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (131 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetUnregisterEventHandler", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (133 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetEnumGamesEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (134 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetSendServerChatCommand", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (135 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetSend135", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (136 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetReceive136", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (137 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetGetPlayerNames", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (138 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetCreateLadderGame", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (139 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetReportGameResult", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (140 - ordBase) * 4); if (rva) { set_name(base + rva, "SNetCheckDataFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (201 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgBeginPaint", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (202 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgBltToWindowI", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (203 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgCheckTimers", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (204 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgCreateDialogIndirectParam", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (205 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgCreateDialogParam", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (206 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgDefDialogProc", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (208 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgDialogBoxIndirectParam", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (209 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgDialogBoxParam", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (210 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgDrawBitmap", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (211 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgEndDialog", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (212 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgEndPaint", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (213 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgKillTimer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (214 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgSetBaseFont", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (215 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgSetBitmapI", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (216 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgSetControlBitmaps", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (217 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgSetCursor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (218 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgSetSystemCursor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (219 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgSetTimer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (220 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgUpdateCursor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (221 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgBltToWindowE", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (222 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgSetBitmapE", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (223 - ordBase) * 4); if (rva) { set_name(base + rva, "SDlgSetLocale", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (251 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileAuthenticateArchive", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (252 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileCloseArchive", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (253 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileCloseFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (254 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileDdaBegin", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (255 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileDdaBeginEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (256 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileDdaDestroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (257 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileDdaEnd", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (258 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileDdaGetPos", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (259 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileDdaGetVolume", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (260 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileDdaInitialize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (261 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileDdaSetVolume", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (262 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileDestroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (263 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileEnableDirectAccess", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (264 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileGetFileArchive", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (265 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileGetFileSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (266 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileOpenArchive", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (267 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileOpenFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (268 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileOpenFileEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (269 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileReadFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (270 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileSetBasePath", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (271 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileSetFilePointer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (272 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileSetLocale", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (273 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileGetBasePath", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (274 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileSetIoErrorMode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (275 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileGetArchiveName", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (276 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileGetFileName", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (277 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileGetArchiveInfo", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (278 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileSetPlatform", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (279 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileLoadFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (280 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileUnloadFile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (281 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileLoadFileEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (282 - ordBase) * 4); if (rva) { set_name(base + rva, "SFilePrioritizeRequest", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (283 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileCancelRequest", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (284 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileSetAsyncBudget", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (285 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileSetDataChunkSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (286 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileEnableSeekOptimization", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (287 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileReadFileEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (288 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileFileExists", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (289 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileFileExistsEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (290 - ordBase) * 4); if (rva) { set_name(base + rva, "SFileReadFileEx2", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (301 - ordBase) * 4); if (rva) { set_name(base + rva, "StormDestroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (302 - ordBase) * 4); if (rva) { set_name(base + rva, "StormGetInstance", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (303 - ordBase) * 4); if (rva) { set_name(base + rva, "StormGetOption", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (304 - ordBase) * 4); if (rva) { set_name(base + rva, "StormSetOption", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (312 - ordBase) * 4); if (rva) { set_name(base + rva, "SBltGetSCode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (313 - ordBase) * 4); if (rva) { set_name(base + rva, "SBltROP3", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (314 - ordBase) * 4); if (rva) { set_name(base + rva, "SBltROP3Clipped", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (315 - ordBase) * 4); if (rva) { set_name(base + rva, "SBltROP3Tiled", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (321 - ordBase) * 4); if (rva) { set_name(base + rva, "SBmpDecodeImage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (323 - ordBase) * 4); if (rva) { set_name(base + rva, "SBmpLoadImage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (324 - ordBase) * 4); if (rva) { set_name(base + rva, "SBmpSaveImage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (325 - ordBase) * 4); if (rva) { set_name(base + rva, "SBmpAllocLoadImage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (326 - ordBase) * 4); if (rva) { set_name(base + rva, "SBmpSaveImageEx", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (331 - ordBase) * 4); if (rva) { set_name(base + rva, "SCodeCompile", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (332 - ordBase) * 4); if (rva) { set_name(base + rva, "SCodeDelete", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (334 - ordBase) * 4); if (rva) { set_name(base + rva, "SCodeExecute", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (335 - ordBase) * 4); if (rva) { set_name(base + rva, "SCodeGetPseudocode", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (341 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawAutoInitialize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (342 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawCaptureScreen", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (343 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawClearSurface", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (344 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawDestroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (345 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawFlipPage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (346 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawGetFrameWindow", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (347 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawGetObjects", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (348 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawGetScreenSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (349 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawGetServiceLevel", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (350 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawLockSurface", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (351 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawManualInitialize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (352 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawMessageBox", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (353 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawPostClose", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (354 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawRealizePalette", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (355 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawSelectGdiSurface", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (356 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawUnlockSurface", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (357 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawUpdatePalette", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (358 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawUpdateScreen", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (359 - ordBase) * 4); if (rva) { set_name(base + rva, "SDrawWaitForVerticalBlank", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (372 - ordBase) * 4); if (rva) { set_name(base + rva, "SEvtDispatch", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (373 - ordBase) * 4); if (rva) { set_name(base + rva, "SEvtRegisterHandler", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (374 - ordBase) * 4); if (rva) { set_name(base + rva, "SEvtUnregisterHandler", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (375 - ordBase) * 4); if (rva) { set_name(base + rva, "SEvtUnregisterType", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (376 - ordBase) * 4); if (rva) { set_name(base + rva, "SEvtPopState", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (377 - ordBase) * 4); if (rva) { set_name(base + rva, "SEvtPushState", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (378 - ordBase) * 4); if (rva) { set_name(base + rva, "SEvtBreakHandlerChain", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (381 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdiBitBlt", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (382 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdiCreateFont", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (383 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdiDeleteObject", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (385 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdiExtTextOut", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (386 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdiImportFont", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (387 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdiLoadFont", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (388 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdiRectangle", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (389 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdiSelectObject", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (390 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdiSetPitch", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (391 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdiTextOut", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (392 - ordBase) * 4); if (rva) { set_name(base + rva, "SGdi392", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (393 - ordBase) * 4); if (rva) { set_name(base + rva, "Ordinal393", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (401 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemAlloc", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (403 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemFree", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (404 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemGetSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (405 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemReAlloc", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (412 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgDispatchMessage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (413 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgDoMessageLoop", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (414 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgRegisterCommand", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (415 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgRegisterKeyDown", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (416 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgRegisterKeyUp", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (417 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgRegisterMessage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (418 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgPopRegisterState", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (419 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgPushRegisterState", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (421 - ordBase) * 4); if (rva) { set_name(base + rva, "SRegLoadData", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (422 - ordBase) * 4); if (rva) { set_name(base + rva, "SRegLoadString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (423 - ordBase) * 4); if (rva) { set_name(base + rva, "SRegLoadValue", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (424 - ordBase) * 4); if (rva) { set_name(base + rva, "SRegSaveData", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (425 - ordBase) * 4); if (rva) { set_name(base + rva, "SRegSaveString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (426 - ordBase) * 4); if (rva) { set_name(base + rva, "SRegSaveValue", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (427 - ordBase) * 4); if (rva) { set_name(base + rva, "SRegGetBaseKey", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (428 - ordBase) * 4); if (rva) { set_name(base + rva, "SRegDeleteValue", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (431 - ordBase) * 4); if (rva) { set_name(base + rva, "STransBlt", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (432 - ordBase) * 4); if (rva) { set_name(base + rva, "STransBltUsingMask", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (433 - ordBase) * 4); if (rva) { set_name(base + rva, "STransCreateI", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (434 - ordBase) * 4); if (rva) { set_name(base + rva, "STransDelete", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (436 - ordBase) * 4); if (rva) { set_name(base + rva, "STransDuplicate", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (437 - ordBase) * 4); if (rva) { set_name(base + rva, "STransIntersectDirtyArray", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (438 - ordBase) * 4); if (rva) { set_name(base + rva, "STransInvertMask", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (439 - ordBase) * 4); if (rva) { set_name(base + rva, "STransLoadI", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (440 - ordBase) * 4); if (rva) { set_name(base + rva, "STransSetDirtyArrayInfo", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (441 - ordBase) * 4); if (rva) { set_name(base + rva, "STransUpdateDirtyArray", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (442 - ordBase) * 4); if (rva) { set_name(base + rva, "STransPointInMask", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (443 - ordBase) * 4); if (rva) { set_name(base + rva, "STransCombineMasks", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (444 - ordBase) * 4); if (rva) { set_name(base + rva, "STransCreateI2", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (445 - ordBase) * 4); if (rva) { set_name(base + rva, "STransCreateE", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (446 - ordBase) * 4); if (rva) { set_name(base + rva, "STrans446", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (447 - ordBase) * 4); if (rva) { set_name(base + rva, "STransLoadE", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (451 - ordBase) * 4); if (rva) { set_name(base + rva, "SVidDestroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (452 - ordBase) * 4); if (rva) { set_name(base + rva, "SVidGetSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (453 - ordBase) * 4); if (rva) { set_name(base + rva, "SVidInitialize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (454 - ordBase) * 4); if (rva) { set_name(base + rva, "SVidPlayBegin", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (455 - ordBase) * 4); if (rva) { set_name(base + rva, "SVidPlayBeginFromMemory", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (456 - ordBase) * 4); if (rva) { set_name(base + rva, "SVidPlayContinue", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (457 - ordBase) * 4); if (rva) { set_name(base + rva, "SVidPlayContinueSingle", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (458 - ordBase) * 4); if (rva) { set_name(base + rva, "SVidPlayEnd", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (459 - ordBase) * 4); if (rva) { set_name(base + rva, "SVidSetVolume", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (461 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrDisplayError", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (462 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrGetErrorStr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (463 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrGetLastError", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (464 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrRegisterMessageSource", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (465 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrSetLastError", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (466 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrReportNamedResourceLeak", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (467 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrReportResourceLeak", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (468 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrSuppressErrors", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (469 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrRegisterHandler", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (470 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrUnregisterHandler", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (472 - ordBase) * 4); if (rva) { set_name(base + rva, "SCmdGetBool", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (473 - ordBase) * 4); if (rva) { set_name(base + rva, "SCmdGetNum", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (474 - ordBase) * 4); if (rva) { set_name(base + rva, "SCmdGetString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (475 - ordBase) * 4); if (rva) { set_name(base + rva, "SCmdProcess", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (476 - ordBase) * 4); if (rva) { set_name(base + rva, "SCmdRegisterArgList", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (477 - ordBase) * 4); if (rva) { set_name(base + rva, "SCmdRegisterArgument", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (478 - ordBase) * 4); if (rva) { set_name(base + rva, "SCmdStringExists", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (479 - ordBase) * 4); if (rva) { set_name(base + rva, "SCmdProcessCommandLine", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (481 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemFindNextBlock", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (482 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemFindNextHeap", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (483 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemGetHeapByCaller", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (484 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemGetHeapByPtr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (485 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemHeapAlloc", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (486 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemHeapCreate", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (487 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemHeapDestroy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (488 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemHeapFree", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (489 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemHeapRealloc", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (490 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemHeapSize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (491 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemCopy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (492 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemFill", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (493 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemMove", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (494 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemZero", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (495 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemCmp", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (496 - ordBase) * 4); if (rva) { set_name(base + rva, "SMem496", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (497 - ordBase) * 4); if (rva) { set_name(base + rva, "SMemDumpState", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (501 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrCopy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (502 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrHash", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (503 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrNCat", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (504 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrTokenize", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (505 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrSearch", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (506 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrLen", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (507 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrDup", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (508 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrCmp", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (509 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrCmpI", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (510 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrUpper", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (511 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgBreakHandlerChain", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (512 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgUnregisterCommand", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (513 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgUnregisterKeyDown", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (514 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgUnregisterKeyUp", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (515 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgUnregisterMessage", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (516 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgGetDispatcher", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (517 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgSetDefaultWindow", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (518 - ordBase) * 4); if (rva) { set_name(base + rva, "SMsgGetDefaultWindow", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (521 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn521", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (523 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn523", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (524 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgnCreateRegion", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (525 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgnDeleteRegion", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (527 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn527", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (528 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn528i", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (529 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn529i", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (530 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn530i", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (531 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn531i", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (532 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn532i", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (533 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn533i", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (534 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn534", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (535 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn535f", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (536 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn536f", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (537 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn537f", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (538 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn538f", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (539 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn539f", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (540 - ordBase) * 4); if (rva) { set_name(base + rva, "SRgn540f", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (541 - ordBase) * 4); if (rva) { set_name(base + rva, "SLogClose", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (542 - ordBase) * 4); if (rva) { set_name(base + rva, "SLogCreate", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (543 - ordBase) * 4); if (rva) { set_name(base + rva, "SLog543", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (544 - ordBase) * 4); if (rva) { set_name(base + rva, "SLogDump", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (545 - ordBase) * 4); if (rva) { set_name(base + rva, "SLogFlush", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (546 - ordBase) * 4); if (rva) { set_name(base + rva, "SLogFlushAll", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (547 - ordBase) * 4); if (rva) { set_name(base + rva, "SLogPend", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (548 - ordBase) * 4); if (rva) { set_name(base + rva, "SLogWrite", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (549 - ordBase) * 4); if (rva) { set_name(base + rva, "SLog549", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (550 - ordBase) * 4); if (rva) { set_name(base + rva, "SLogCriticalLog", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (551 - ordBase) * 4); if (rva) { set_name(base + rva, "SCompCompress", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (552 - ordBase) * 4); if (rva) { set_name(base + rva, "SCompDecompress", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (561 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrDisplayAppFatal", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (562 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrDisplayErrorFmt", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (563 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrIsDisplayingError", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (564 - ordBase) * 4); if (rva) { set_name(base + rva, "SErrPrepareAppFatal", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (571 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrChr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (572 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrChrR", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (573 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrToDouble", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (574 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrToFloat", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (575 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrToInt", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (576 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrToUnsigned", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (577 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrToInt64", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (578 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrPrintf", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (579 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrLower", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (580 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrHash64", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (581 - ordBase) * 4); if (rva) { set_name(base + rva, "SStrVPrintf", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (582 - ordBase) * 4); if (rva) { set_name(base + rva, "SHashString", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (601 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigAdd", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (602 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigAnd", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (603 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigCompare", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (604 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigCopy", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (605 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigDec", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (606 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigDel", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (607 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigDiv", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (608 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigFindPrime", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (609 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigFromBinary", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (610 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigFromStr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (611 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigFromStream", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (612 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigFromUnsigned", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (613 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigGcd", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (614 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigInc", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (615 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigInvMod", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (616 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigIsEven", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (617 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigIsOdd", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (618 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigIsOne", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (619 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigIsPrime", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (620 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigIsZero", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (621 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigMod", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (622 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigMul", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (623 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigMulMod", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (624 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigNew", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (625 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigNot", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (626 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigOr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (627 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigPow", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (628 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigPowMod", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (629 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigRand", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (630 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigSet2Exp", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (631 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigSetOne", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (632 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigSetZero", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (633 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigShl", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (634 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigShr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (635 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigSquare", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (636 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigSub", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (637 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigToBinaryArray", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (638 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigToBinaryBuffer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (639 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigToBinaryPtr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (640 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigToStrArray", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (641 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigToStrBuffer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (642 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigToStrPtr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (643 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigToStreamArray", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (644 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigToStreamBuffer", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (645 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigToStreamPtr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (646 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigToUnsigned", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (647 - ordBase) * 4); if (rva) { set_name(base + rva, "SBigXor", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (901 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniConvertUTF16to8Len", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (902 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniConvertUTF16to8", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (903 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniConvertUTF8to16Len", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (904 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniConvertUTF8to16", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (905 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniS905", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (906 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniS906", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (907 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniFindAfterUTF8Chr", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (908 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniFindUTF8ChrStart", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (909 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniConvertUTF16To909", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (910 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniConvertUTF16To910", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (911 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniConvertUTF16To911", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (912 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniConvert912", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (913 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniConvert913", 0x880); renamed++; } else skipped++;
    rva = Dword(addrFuncs + (914 - ordBase) * 4); if (rva) { set_name(base + rva, "SUniConvert914", 0x880); renamed++; } else skipped++;

    Message("[Storm] Done: %d renamed, %d skipped (rva==0)\n", renamed, skipped);
}

#ifndef D2MOO_ALL_IDC
static main() { Apply_Storm(); }
#endif
