# gen_ida_idc.ps1
# Generates IDA IDC scripts from D2MOO .def files.
# TARGET: IDA process dump (all DLLs loaded as segments).
#
# Strategy: find the DLL segment dynamically by name (FirstSeg/NextSeg),
# then parse the PE export table at that base.
# No hardcoded base address -- works regardless of where the DLL loaded.
#
# Usage:
#   .\gen_ida_idc.ps1                          # all DLLs
#   .\gen_ida_idc.ps1 -Dlls D2Common,D2Game   # specific DLLs
#   .\gen_ida_idc.ps1 -OutputDir C:\tmp\idc    # custom output dir
#
# IDA compatibility: 7.x+  (set_name / Dword / Word / get_segm_name)
# IDA 6.x: replace set_name(a,n,0x880) with MakeNameEx(a,n,0x800)

param(
    [string]   $SourceDir = "$PSScriptRoot\..\source",
    [string]   $OutputDir = "$PSScriptRoot\idc",
    [string[]] $Dlls      = @("D2Common","D2Game","D2Client","Fog",
                               "D2Win","D2gfx","D2Lang","D2Net",
                               "D2sound","Storm","D2CMP")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir | Out-Null
}

function ConvertDefToIDC {
    param(
        [string] $DefPath,
        [string] $DllName,     # e.g. "D2Common"
        [string] $SegPattern,  # substring to search in segment name, e.g. "D2Common"
        [string] $OutPath
    )

    $rawlines = Get-Content $DefPath -Encoding UTF8
    $entries  = [System.Collections.Generic.List[PSCustomObject]]::new()

    foreach ($line in $rawlines) {
        if ($line -match '^\s*$')                    { continue }
        if ($line -match '^\s*;')                    { continue }
        if ($line -match '^\s*(LIBRARY|EXPORTS)\b')  { continue }
        if ($line -match '^\s+(\S+)\s+@(\d+)') {
            $entries.Add([PSCustomObject]@{
                Name    = $Matches[1]
                Ordinal = [int]$Matches[2]
            })
        }
    }

    if ($entries.Count -eq 0) {
        Write-Warning "$DllName : no entries found in $DefPath -- skipped."
        return
    }

    $out = [System.Collections.Generic.List[string]]::new($entries.Count * 1 + 60)

    $out.Add('#include <idc.idc>')
    $out.Add('')
    $out.Add("// =============================================================")
    $out.Add("// $DllName.idc  --  generated by gen_ida_idc.ps1 (D2MOO)")
    $out.Add("// Source : $DllName.1.10f.def  ($($entries.Count) exported symbols)")
    $out.Add("//")
    $out.Add("// TARGET: IDA process dump")
    $out.Add("//")
    $out.Add("// Finds the DLL base by scanning IDA segments for name containing")
    $out.Add("// `"$SegPattern`" -- no hardcoded address needed.")
    $out.Add("//")
    $out.Add("// Then parses the PE export table at that base and applies names.")
    $out.Add("//   funcAddr = base + Dword(addrOfFunctions + (ordinal - ordBase) * 4)")
    $out.Add("//")
    $out.Add("// IDA 6.x: replace  set_name(a,n,0x880)  with  MakeNameEx(a,n,0x800)")
    $out.Add("// =============================================================")
    $out.Add('')
    $out.Add('static main()')
    $out.Add('{')
    $out.Add('    // --- Find module base via segment name ---')
    $out.Add('    auto base = BADADDR;')
    $out.Add('    auto seg;')
    $out.Add('    for (seg = FirstSeg(); seg != BADADDR; seg = NextSeg(seg)) {')
    $out.Add("        if (strstr(get_segm_name(seg), `"$SegPattern`") != -1) {")
    $out.Add('            base = SegStart(seg);')
    $out.Add('            break;')
    $out.Add('        }')
    $out.Add('    }')
    $out.Add('    if (base == BADADDR) {')
    $out.Add("        Message(`"[$DllName] ERROR: no segment with name containing '$SegPattern'.\n`");")
    $out.Add("        Message(`"[$DllName] Check segment names with: Edit > Segments\n`");")
    $out.Add('        return;')
    $out.Add('    }')
    $out.Add('')
    $out.Add('    // --- Parse PE header ---')
    $out.Add('    auto peBase = base + Dword(base + 0x3C);')
    $out.Add('    if (Dword(peBase) != 0x00004550) {')
    $out.Add("        Message(`"[$DllName] ERROR: invalid PE signature at 0x%X (base=0x%X)\n`", peBase, base);")
    $out.Add("        Message(`"[$DllName] The first matching segment does not hold the PE header.\n`");")
    $out.Add("        Message(`"[$DllName] Try running ParseExports.idc first to confirm the correct base.\n`");")
    $out.Add('        return;')
    $out.Add('    }')
    $out.Add('')
    $out.Add('    // --- Export Directory ---')
    $out.Add('    auto exportRVA = Dword(peBase + 0x18 + 0x60);  // OptionalHeader + DataDirectory[0]')
    $out.Add('    if (exportRVA == 0) {')
    $out.Add("        Message(`"[$DllName] ERROR: no export directory found.\n`");")
    $out.Add('        return;')
    $out.Add('    }')
    $out.Add('    auto exportDir   = base + exportRVA;')
    $out.Add('    auto ordBase     = Dword(exportDir + 0x10);  // IMAGE_EXPORT_DIRECTORY.Base')
    $out.Add('    auto addrFuncs   = base + Dword(exportDir + 0x1C);  // .AddressOfFunctions')
    $out.Add('')
    $out.Add("    Message(`"[$DllName] base=0x%X  ordBase=%d  addrFuncs=0x%X\n`", base, ordBase, addrFuncs);")
    $out.Add('')
    $out.Add('    // --- Apply names ---')
    $out.Add('    auto rva;')
    $out.Add('    auto renamed = 0;')
    $out.Add('    auto skipped = 0;')
    $out.Add('')

    foreach ($e in $entries) {
        $out.Add("    rva = Dword(addrFuncs + ($($e.Ordinal) - ordBase) * 4); if (rva) { set_name(base + rva, `"$($e.Name)`", 0x880); renamed++; } else skipped++;")
    }

    $out.Add('')
    $out.Add("    Message(`"[$DllName] Done: %d renamed, %d skipped (rva==0)\n`", renamed, skipped);")
    $out.Add('}')

    [System.IO.File]::WriteAllLines($OutPath, $out, [System.Text.ASCIIEncoding]::new())
    Write-Host "[OK] $DllName -- $($entries.Count) entries  ->  $OutPath"
}

Write-Host ""
Write-Host "=== gen_ida_idc.ps1  (D2MOO -> IDA IDC, process dump) ==="
Write-Host ""

# DLL name -> segment name pattern (as it appears in IDA segment names)
$SegPatterns = @{
    "D2Common" = "D2Common"
    "D2Game"   = "D2Game"
    "D2Client" = "D2Client"
    "Fog"      = "Fog"
    "D2Win"    = "D2Win"
    "D2Gfx"    = "D2Gfx"
    "D2Lang"   = "D2Lang"
    "D2Net"    = "D2Net"
    "D2Sound"  = "D2Sound"
    "Storm"    = "Storm"
    "D2CMP"    = "D2CMP"
}

foreach ($dll in $Dlls) {
    $defPath = Join-Path $SourceDir "$dll\definitions\$dll.1.10f.def"
    if (-not (Test-Path $defPath)) {
        Write-Warning "$dll : .def not found at $defPath -- skipped."
        continue
    }
    $pat     = if ($SegPatterns.ContainsKey($dll)) { $SegPatterns[$dll] } else { $dll }
    $outPath = Join-Path $OutputDir "$dll.idc"
    ConvertDefToIDC -DefPath $defPath -DllName $dll -SegPattern $pat -OutPath $outPath
}

Write-Host ""
Write-Host "Done. IDC files in: $OutputDir"
Write-Host ""
Write-Host "IDA usage:"
Write-Host "  File > Script file...  (Alt+F7)  -> select .idc"
Write-Host "  Check Output window for base/ordBase confirmation and rename count."
Write-Host "  If 'segment not found': check exact segment names via Edit > Segments"
Write-Host "  and update the SegPattern in gen_ida_idc.ps1 accordingly."

